import { z } from 'zod';
import type { Env } from '../types';
import { COMMANDS, quizRpc } from './service';
export function registerQuizTools(server:any,env:Env,request:Request){
  const output=(v:any)=>({isError:v?.ok===false,content:[{type:'text',text:JSON.stringify(v)}]});
  const call=async(op:string,p:any)=>{try{return output(await quizRpc(env,request,op,p));}catch(e){return output({ok:false,error:e instanceof Error?e.message:'QUIZ_ERROR'});}};
  const register=(name:string,description:string,schema:any,op:string,readOnly=false,map=(p:any)=>p)=>server.registerTool(name,{description,inputSchema:schema,annotations:{readOnlyHint:readOnly,destructiveHint:false,idempotentHint:true,openWorldHint:false}},(p:any)=>call(op,map(p)));
  const id=z.string().min(1).max(100),obj=z.record(z.string(),z.unknown());
  const execute={id,request_id:id.describe('Unique identifier; reuse exactly on retry to avoid duplicate actions.'),expected_revision:z.number().int().min(0).optional()};
  const inline=async(data:any,enabled=true)=>{const result:any=output(data),url=data.result?.preview_url;if(enabled&&data.status==='SUCCEEDED'&&url){const u=new URL(url);if(u.origin===new URL(request.url).origin&&u.pathname.startsWith('/quiz/media/')){const {serveQuizMedia}=await import('./service');const r=await serveQuizMedia(env,new Request(url),u.pathname.split('/').pop()!);if(r.ok&&Number(r.headers.get('content-length'))<=8_000_000&&r.headers.get('content-type')==='image/png'){const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));result.content.push({type:'image',mimeType:'image/png',data:btoa(binary)});}}}return result;};
  register('quiz_comandos','Descubra comandos e disponibilidade do executor. Use execute get_schema para obter TODOS os campos reais do editor. Não usa materialização no chat.',{},'catalog',true);
  register('quiz_listar','Lista quizzes persistidos, revisões e disponibilidade do executor.',{limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().min(0).optional()},'list',true);
  register('quiz_criar','Cria um quiz. id permite criação idempotente; project_id vincula a um projeto da Library.',{id,title:z.string().max(160),project_id:id.optional()},'create');
  register('quiz_obter_estado','Leitura imediata persistida, sem precisar abrir o editor. Padrão compacto; scene retorna TODOS os campos de uma cena; scenes pagina; full apenas backup/diagnóstico.',{id,if_revision:z.number().int().optional(),scene:z.number().int().min(1).optional(),scenes:z.boolean().optional(),offset:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(50).optional(),full:z.boolean().optional()},'read',true);
  register('quiz_executar','Executa QUALQUER comando do Quiz no editor real, inclusive áudio, textos, camadas, importação, lote, PNG e MP4. Retorna job id rapidamente; consultar quiz_operacao até SUCCEEDED/FAILED/CANCELLED. QUEUED não significa executado. Requer executor online.',{...execute,op:z.enum(COMMANDS),args:obj.optional()},'execute',false,p=>({...p,command:{...(p.args||{}),op:p.op}}));
  register('quiz_alterar','Patch parcial da cena, preservando todos os outros campos. Imagens por asset_id da Library. Resultado assíncrono.',{...execute,scene:z.number().int().min(1),patch:obj},'execute',false,p=>({...p,command:{op:'apply',scene:p.scene,patch:p.patch}}));
  register('quiz_alterar_lote','Aplica até 200 comandos de edição atomicamente, com rollback integral se qualquer operação falhar.',{...execute,operations:z.array(obj).min(1).max(200)},'execute',false,p=>({...p,command:{op:'apply_batch',operations:p.operations}}));
  server.registerTool('quiz_ver',{description:'Produz o PNG real, aguarda brevemente e, quando concluído, já o devolve inline para inspeção visual. Também retorna URLs; não usa materialização do chat.',inputSchema:{...execute,scene:z.number().int().min(1).optional(),time:z.number().min(0).optional(),wait_ms:z.number().int().min(0).max(45000).optional()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async(p:any)=>{try{const queued=await quizRpc(env,request,'execute',{...p,command:{op:'get_visual',scene:p.scene,time:p.time}});const end=Date.now()+(p.wait_ms??25000);let data:any=queued;while(Date.now()<end){data=await quizRpc(env,request,'job',{job_id:queued.id});if(['SUCCEEDED','FAILED','CANCELLED'].includes(data.status))break;await new Promise(r=>setTimeout(r,400));}return inline(data,true);}catch(e){return output({ok:false,error:e instanceof Error?e.message:'QUIZ_ERROR'});}});
  register('quiz_gerar_mp4','Gera MP4 real pelo executor online. scope=scene exporta uma cena; scope=project exporta o Quiz inteiro. Consulte quiz_operacao até SUCCEEDED e use download_url.',{...execute,scope:z.enum(['scene','project']).default('project'),scene:z.number().int().min(1).optional(),format:z.enum(['16:9','9:16']).optional()},'execute',false,p=>({...p,command:{op:p.scope==='scene'?'export_scene_mp4':'export_project_mp4',scene:p.scene,format:p.format}}));
  register('quiz_cancelar','Cancela uma operação pendente ou solicita interrupção de uma exportação ativa.',{job_id:id},'cancel');
  server.registerTool('quiz_operacao',{description:'Consulta resultado/erro real e links. inline_preview=true devolve PNG dentro do próprio MCP quando disponível, sem baixar arquivo para o chat.',inputSchema:{job_id:id,inline_preview:z.boolean().optional()},annotations:{readOnlyHint:true,idempotentHint:true,openWorldHint:false}},async(p:any)=>{
    try{const data=await quizRpc(env,request,'job',p);return inline(data,p.inline_preview!==false);
    }catch(e){return output({ok:false,error:e instanceof Error?e.message:'QUIZ_ERROR'});}
  });
}
