import type { AssetExportJob, Env } from "../types";
import { createSignedAssetExportUrl, validSignedAssetExportRequest } from "./auth";
import { id, nowMs } from "./ids";
import { zipStream, type ZipEntry } from "./production";

function clean(v:unknown){return String(v??"").trim();}
function safeName(v:string){return v.replace(/[\\/:*?"<>|\x00-\x1f]+/g,"-").replace(/\s+/g," ").trim().slice(0,160)||"arquivo";}
async function hashIds(ids:string[]){const canonical=[...ids].sort().join("\n");const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}

export async function queueAssetExport(env:Env,input:{assetIds:string[];name?:string;operationId?:string}){
  const assetIds=[...new Set((input.assetIds||[]).map(String).map(clean).filter(Boolean))].slice(0,500);if(!assetIds.length)return{error:"ASSET_IDS_REQUIRED",status:400}as const;
  const placeholders=assetIds.map(()=>"?").join(",");const rows=await env.DB.prepare(`SELECT id,name,original_name,r2_key,mime_type,size_bytes FROM assets WHERE id IN (${placeholders}) ORDER BY id`).bind(...assetIds).all<Record<string,unknown>>();const found=rows.results||[];const foundIds=new Set(found.map(r=>clean(r.id))),missing=assetIds.filter(x=>!foundIds.has(x));if(!found.length)return{error:"NO_ASSETS_FOUND",missing,status:404}as const;
  const setHash=await hashIds(found.map(r=>clean(r.id)));const now=nowMs();const existing=await env.DB.prepare("SELECT * FROM v2_asset_exports WHERE asset_set_hash=? AND status='READY' AND expires_reuse_at>? ORDER BY created_at DESC LIMIT 1").bind(setHash,now).first<Record<string,unknown>>();if(existing)return{...existing,reused:true,missing,httpStatus:202}as const;
  const exportId=id("AEXP"),operationId=clean(input.operationId)||id("OP"),fileName=safeName(clean(input.name)||`corvo-assets-${found.length}.zip`).replace(/\.zip$/i,"")+".zip",ts=nowMs();
  await env.DB.batch([
    env.DB.prepare("INSERT INTO v2_asset_exports (id,operation_id,asset_set_hash,asset_ids_json,status,file_name,created_at,updated_at) VALUES (?,?,?,?, 'QUEUED',?,?,?)").bind(exportId,operationId,setHash,JSON.stringify(found.map(r=>clean(r.id))),fileName,ts,ts),
    env.DB.prepare("INSERT INTO v2_ingest_operations (id,type,status,requested,succeeded,failed,payload_json,created_at,updated_at) VALUES (?,'EXPORT_ASSETS','QUEUED',1,0,0,?,?,?)").bind(operationId,JSON.stringify({exportId,assetIds:found.map(r=>r.id)}),ts,ts),
  ]);
  await env.MATERIALIZE_QUEUE.send({kind:"EXPORT_ASSETS",operationId,exportId} satisfies AssetExportJob);
  return{export_id:exportId,operation_id:operationId,status:"QUEUED",assets:found.length,missing,httpStatus:202};
}

export async function processAssetExportJob(env:Env,job:AssetExportJob){const row=await env.DB.prepare("SELECT * FROM v2_asset_exports WHERE id=?").bind(job.exportId).first<Record<string,unknown>>();if(!row)throw new Error("ASSET_EXPORT_NOT_FOUND");if(clean(row.status)==="READY")return row;const ids=JSON.parse(clean(row.asset_ids_json)||"[]") as string[];const placeholders=ids.map(()=>"?").join(",");const assets=ids.length?(await env.DB.prepare(`SELECT * FROM assets WHERE id IN (${placeholders}) ORDER BY id`).bind(...ids).all<Record<string,unknown>>()).results||[]:[];const used=new Set<string>(),entries:ZipEntry[]=[];for(const a of assets){let name=safeName(clean(a.original_name)||`${clean(a.name)||clean(a.id)}.bin`);if(used.has(name)){const dot=name.lastIndexOf("."),stem=dot>0?name.slice(0,dot):name,ext=dot>0?name.slice(dot):"";name=`${stem}-${clean(a.id)}${ext}`;}used.add(name);entries.push({name,open:async()=>{const obj=await env.MEDIA.get(clean(a.r2_key));if(!obj)throw new Error(`R2_OBJECT_MISSING:${clean(a.id)}`);return obj.body;}});}entries.push({name:"EXPORT.json",open:async()=>new TextEncoder().encode(JSON.stringify({export_id:job.exportId,assets:assets.map(a=>({id:a.id,name:a.name,universe:a.universe,r2_key:a.r2_key})),generated_at:new Date().toISOString()},null,2))});const r2Key=`exports/assets/${job.exportId}/${safeName(clean(row.file_name)||`${job.exportId}.zip`)}`,ts=nowMs();try{const {stream}=zipStream(entries);await env.MEDIA.put(r2Key,stream,{httpMetadata:{contentType:"application/zip"},customMetadata:{exportId:job.exportId}});const head=await env.MEDIA.head(r2Key);await env.DB.batch([env.DB.prepare("UPDATE v2_asset_exports SET status='READY',r2_key=?,size_bytes=?,ready_at=?,expires_reuse_at=?,updated_at=? WHERE id=?").bind(r2Key,Number(head?.size||0),ts,ts+48*3600_000,ts,job.exportId),env.DB.prepare("UPDATE v2_ingest_operations SET status='COMPLETED',succeeded=1,updated_at=? WHERE id=?").bind(ts,job.operationId)]);return{export_id:job.exportId,status:"READY",r2_key:r2Key,size_bytes:Number(head?.size||0)};}catch(error){const message=error instanceof Error?error.message:String(error);await env.DB.batch([env.DB.prepare("UPDATE v2_asset_exports SET status='FAILED',error=?,updated_at=? WHERE id=?").bind(message,ts,job.exportId),env.DB.prepare("UPDATE v2_ingest_operations SET status='FAILED',failed=1,error=?,updated_at=? WHERE id=?").bind(message,ts,job.operationId)]);throw error;}}

export async function getAssetExportLink(request:Request,env:Env,exportId:string,ttlMinutes=30){const row=await env.DB.prepare("SELECT * FROM v2_asset_exports WHERE id=?").bind(exportId).first<Record<string,unknown>>();if(!row)return{error:"EXPORT_NOT_FOUND",status:404}as const;if(clean(row.status)!=="READY")return{error:`EXPORT_NOT_READY:${clean(row.status)}`,status:409}as const;const ttl=Math.max(1,Math.min(ttlMinutes,60))*60;return{export_id:exportId,status:"READY",download_url:await createSignedAssetExportUrl(request,exportId,env,ttl),filename:row.file_name,size_bytes:Number(row.size_bytes||0),expires_at:new Date(Date.now()+ttl*1000).toISOString(),direct_to_pc:true};}
export async function serveAssetExport(request:Request,env:Env,exportId:string){if(!(await validSignedAssetExportRequest(request,exportId,env)))return new Response("Forbidden",{status:403});const row=await env.DB.prepare("SELECT * FROM v2_asset_exports WHERE id=?").bind(exportId).first<Record<string,unknown>>();if(!row?.r2_key)return new Response("Not found",{status:404});const obj=await env.MEDIA.get(clean(row.r2_key));if(!obj)return new Response("Not found",{status:404});await env.DB.prepare("UPDATE v2_asset_exports SET download_count=download_count+1,updated_at=? WHERE id=?").bind(nowMs(),exportId).run();return new Response(obj.body,{headers:{"content-type":"application/zip","content-disposition":`attachment; filename="${safeName(clean(row.file_name)||`${exportId}.zip`)}"`,"cache-control":"private, max-age=60"}});}
export async function exportFrozenMaterializationBatch(env:Env,batchId:string,name?:string){const rows=await env.DB.prepare("SELECT frozen_asset_id FROM materialization_items WHERE batch_id=? AND frozen_asset_id IS NOT NULL ORDER BY created_at").bind(batchId).all<{frozen_asset_id:string}>();const ids=(rows.results||[]).map(r=>r.frozen_asset_id);if(!ids.length)return{error:"NO_FROZEN_ASSETS",status:409}as const;return queueAssetExport(env,{assetIds:ids,name:name||`${batchId}.zip`});}
