import type { CollectionJob, CorvoQueueJob, Env } from "../types";
import { enqueueFastPushItems } from "./ingest";
import { id, nowMs } from "./ids";
import { safeRemoteUrl } from "./net";

function clean(v:unknown){return String(v??"").trim();}
function parse<T>(v:unknown,f:T):T{try{return typeof v==="string"?JSON.parse(v) as T:(v as T??f)}catch{return f}}
function bool(v:unknown){return v===true||v===1||clean(v)==="1"||clean(v).toLowerCase()==="true";}
function normalizedUrl(v:string){try{const u=new URL(v);u.hash="";for(const key of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(key))u.searchParams.delete(key);return u.toString()}catch{return v}}
function getPath(input:unknown,path:string):unknown[]{if(!path)return[];let nodes:unknown[]=[input];for(const segment of path.split(".").filter(Boolean)){const next:unknown[]=[];for(const node of nodes){if(segment==="*"){if(Array.isArray(node))next.push(...node);else if(node&&typeof node==="object")next.push(...Object.values(node as Record<string,unknown>));continue;}if(Array.isArray(node)&&/^\d+$/.test(segment)){next.push(node[Number(segment)]);continue;}if(node&&typeof node==="object"&&segment in (node as Record<string,unknown>))next.push((node as Record<string,unknown>)[segment]);}nodes=next;}return nodes.flatMap(n=>Array.isArray(n)?n:[n]);}
function parseTerms(text:string){const out:Array<{term:string;quantity:number;kind:string;universe:string|null}>=[];for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith("#"))continue;const [term,q,kind,universe]=line.split("|").map(v=>v?.trim());if(!term)continue;out.push({term,quantity:Math.max(1,Math.min(Number(q)||10,500)),kind:kind||"qualquer",universe:universe||null});}return out.slice(0,500);}
async function event(env:Env,batchId:string,eventName:string,status:string,detail:unknown,termId?:string,sourceId?:string){await env.DB.prepare("INSERT INTO v2_collection_events (id,batch_id,term_id,source_id,event,status,detail,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id("CEV"),batchId,termId||null,sourceId||null,eventName,status,JSON.stringify(detail??{}),nowMs()).run();}

export async function configureCollectionSource(env:Env,input:{id?:string;name:string;baseUrl:string;method?:string;queryParam?:string;limitParam?:string;imagePath:string;thumbnailPath?:string;priority?:number;active?:boolean;apiKeyEnv?:string;apiKeyHeader?:string;headers?:Record<string,string>;userAgent?:string;timeoutMs?:number;domain?:string;note?:string}){
  const url=safeRemoteUrl(input.baseUrl);if(!url)return{error:"UNSAFE_BASE_URL",status:400}as const;if(!clean(input.name)||!clean(input.imagePath))return{error:"NAME_AND_IMAGE_PATH_REQUIRED",status:400}as const;
  const sourceId=clean(input.id)||id("SRC"),ts=nowMs(),existing=await env.DB.prepare("SELECT id FROM collection_sources WHERE id=?").bind(sourceId).first();
  const values=[clean(input.name),url.toString(),clean(input.method||"GET").toUpperCase(),clean(input.queryParam||"q"),clean(input.limitParam||"limit"),clean(input.imagePath),clean(input.thumbnailPath)||null,Math.max(1,Math.min(Number(input.priority||3),10)),input.active===false?0:1,clean(input.apiKeyEnv)||null,clean(input.apiKeyHeader)||null,input.note||null,JSON.stringify(input.headers||{}),input.userAgent||"CorvoLibraryV2/1.0",Math.max(1000,Math.min(Number(input.timeoutMs||25000),60000)),input.domain||"MULTI",ts,sourceId];
  if(existing)await env.DB.prepare("UPDATE collection_sources SET name=?,base_url=?,method=?,query_param=?,limit_param=?,image_path=?,thumbnail_path=?,priority=?,active=?,api_key_env=?,api_key_header=?,note=?,headers_json=?,user_agent=?,timeout_ms=?,domain=?,configured=1,updated_at=? WHERE id=?").bind(...values).run();
  else await env.DB.prepare("INSERT INTO collection_sources (id,name,base_url,method,query_param,limit_param,image_path,thumbnail_path,priority,active,api_key_env,api_key_header,note,headers_json,user_agent,timeout_ms,domain,configured,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)").bind(sourceId,...values.slice(0,16),ts,ts).run();
  return{ok:true,id:sourceId,updated:Boolean(existing)};
}

export async function listCollectionSources(env:Env){const rows=await env.DB.prepare("SELECT id,name,base_url,method,query_param,limit_param,image_path,thumbnail_path,priority,active,api_key_env,api_key_header,note,query_count,found_count,unique_count,materialized_count,failure_count,total_duration_ms,headers_json,user_agent,timeout_ms,domain,configured,updated_at FROM collection_sources ORDER BY active DESC,priority ASC,name ASC").all<Record<string,unknown>>();return{items:(rows.results||[]).map(r=>({...r,headers:parse(r.headers_json,{})}))};}

export async function createCollectionBatch(env:Env,input:{name?:string;termsText:string;maxUrlsPerTerm?:number;maxSourcesPerTerm?:number;maxRoundsPerTerm?:number;maxTermMinutes?:number;maxTotalMinutes?:number;nightMode?:boolean}){
  const terms=parseTerms(input.termsText);if(!terms.length)return{error:"NO_VALID_TERMS",status:400}as const;const batchId=id("COL"),ts=nowMs(),total=terms.reduce((n,t)=>n+t.quantity,0);
  const statements=[env.DB.prepare("INSERT INTO collection_batches (id,name,status,terms_text,max_urls_per_term,max_sources_per_term,max_rounds_per_term,max_term_minutes,max_total_minutes,total_terms,total_target,total_collected,cancelled,created_at,updated_at,night_mode) VALUES (?,?,'CRIADO',?,?,?,?,?,?,?, ?,0,0,?,?,?)").bind(batchId,input.name||`Coleta ${new Date(ts).toISOString()}`,input.termsText,Math.max(1,Math.min(input.maxUrlsPerTerm||100,500)),Math.max(1,Math.min(input.maxSourcesPerTerm||20,50)),Math.max(1,Math.min(input.maxRoundsPerTerm||5,20)),Math.max(1,Math.min(input.maxTermMinutes||45,240)),Math.max(1,Math.min(input.maxTotalMinutes||480,1440)),terms.length,total,ts,ts,input.nightMode===false?0:1)];
  for(const t of terms)statements.push(env.DB.prepare("INSERT INTO collection_terms (id,batch_id,term,target_quantity,kind,universe,status,collected_count,attempts,rounds,source_cursor,updated_at) VALUES (?,?,?,?,?,?,'PENDENTE',0,0,0,0,?)").bind(id("TERM"),batchId,t.term,t.quantity,t.kind,t.universe,ts));await env.DB.batch(statements);await event(env,batchId,"BATCH_CREATED","CRIADO",{terms:terms.length,target:total});return{batchId,status:"CRIADO",terms:terms.length,target:total};
}

export async function enqueueCollection(env:Env,input:{batchId:string;rounds?:number;operationId?:string}){const batch=await env.DB.prepare("SELECT * FROM collection_batches WHERE id=?").bind(input.batchId).first<Record<string,unknown>>();if(!batch)return{error:"BATCH_NOT_FOUND",status:404}as const;if(bool(batch.cancelled))return{error:"BATCH_CANCELLED",status:409}as const;const operationId=clean(input.operationId)||id("OP"),existing=await env.DB.prepare("SELECT id,status FROM v2_ingest_operations WHERE id=?").bind(operationId).first<Record<string,unknown>>();if(existing)return{accepted:true,operationId,batchId:input.batchId,status:existing.status,idempotent:true,httpStatus:202}as const;const ts=nowMs();await env.DB.batch([env.DB.prepare("INSERT INTO v2_ingest_operations (id,type,status,requested,succeeded,failed,payload_json,created_at,updated_at) VALUES (?,'COLLECTION_TICK','QUEUED',1,0,0,?,?,?)").bind(operationId,JSON.stringify({batchId:input.batchId,rounds:input.rounds||1}),ts,ts),env.DB.prepare("UPDATE collection_batches SET status='EM_EXECUCAO',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").bind(ts,ts,input.batchId),env.DB.prepare("INSERT INTO v2_control_jobs (id,operation_id,kind,status,payload_json,created_at,updated_at) VALUES (?,?,'COLLECTION_TICK','QUEUED',?,?,?)").bind(id("JOB"),operationId,JSON.stringify({batchId:input.batchId}),ts,ts)]);await env.MATERIALIZE_QUEUE.send({kind:"COLLECTION_TICK",operationId,batchId:input.batchId,rounds:Math.max(1,Math.min(input.rounds||1,10))} satisfies CorvoQueueJob);await event(env,input.batchId,"COLLECTION_QUEUED","QUEUED",{operationId});return{accepted:true,operationId,batchId:input.batchId,status:"QUEUED",httpStatus:202}as const;}

async function querySource(env:Env,source:Record<string,unknown>,term:Record<string,unknown>,limit:number){const started=Date.now(),base=safeRemoteUrl(clean(source.base_url));if(!base)throw new Error("UNSAFE_SOURCE_URL");if(clean(source.method).toUpperCase()!=="GET")throw new Error("ONLY_GET_SOURCE_SUPPORTED_V2");base.searchParams.set(clean(source.query_param)||"q",clean(term.term));base.searchParams.set(clean(source.limit_param)||"limit",String(limit));const headers=new Headers(parse<Record<string,string>>(source.headers_json,{}));headers.set("user-agent",clean(source.user_agent)||"CorvoLibraryV2/1.0");const apiEnv=clean(source.api_key_env),apiHeader=clean(source.api_key_header);if(apiEnv&&apiHeader){const secret=(env as unknown as Record<string,unknown>)[apiEnv];if(!secret)throw new Error(`SOURCE_SECRET_BINDING_MISSING:${apiEnv}`);headers.set(apiHeader,String(secret));}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.max(1000,Math.min(Number(source.timeout_ms||25000),60000)));try{const response=await fetch(base.toString(),{headers,signal:controller.signal,redirect:"follow"});if(!response.ok)throw new Error(`SOURCE_HTTP_${response.status}`);const json=await response.json();const imageValues=getPath(json,clean(source.image_path)).map(clean).filter(Boolean);const thumbs=clean(source.thumbnail_path)?getPath(json,clean(source.thumbnail_path)).map(clean):[];const items=[] as Array<{url:string;thumbnail?:string}>;for(let i=0;i<imageValues.length&&items.length<limit;i++){const safe=safeRemoteUrl(imageValues[i]);if(safe)items.push({url:safe.toString(),thumbnail:safeRemoteUrl(thumbs[i])?.toString()});}return{items,durationMs:Date.now()-started};}finally{clearTimeout(timer);}}

export async function processCollectionJob(env:Env,job:CollectionJob){const start=nowMs();await env.DB.batch([env.DB.prepare("UPDATE v2_ingest_operations SET status='PROCESSING',updated_at=? WHERE id=?").bind(start,job.operationId),env.DB.prepare("UPDATE v2_control_jobs SET status='PROCESSING',attempts=attempts+1,updated_at=? WHERE operation_id=? AND kind='COLLECTION_TICK'").bind(start,job.operationId)]);let discovered=0,failed=0,materializeOps=0;const batch=await env.DB.prepare("SELECT * FROM collection_batches WHERE id=?").bind(job.batchId).first<Record<string,unknown>>();if(!batch)throw new Error("BATCH_NOT_FOUND");const terms=await env.DB.prepare("SELECT * FROM collection_terms WHERE batch_id=? AND status NOT IN ('CONCLUIDO','CANCELADO') ORDER BY updated_at ASC LIMIT 100").bind(job.batchId).all<Record<string,unknown>>();const sources=await env.DB.prepare("SELECT * FROM collection_sources WHERE active=1 AND configured=1 ORDER BY priority ASC,id ASC LIMIT ?").bind(Number(batch.max_sources_per_term||20)).all<Record<string,unknown>>();
  for(const term of terms.results||[]){let termAdded=0;for(let round=0;round<job.rounds;round++){if(termAdded>=Number(term.target_quantity||0))break;for(const source of sources.results||[]){if(termAdded>=Number(term.target_quantity||0))break;const runId=id("CRUN"),ts=nowMs();try{const remain=Math.max(1,Math.min(Number(batch.max_urls_per_term||100),Number(term.target_quantity||10)-Number(term.collected_count||0)-termAdded));const q=await querySource(env,source,term,remain);let unique=0;const pushItems=[] as NonNullable<import("../types").FastPushBody["urls"]>;for(const candidate of q.items){const normalized=normalizedUrl(candidate.url);const exists=await env.DB.prepare("SELECT id FROM collection_candidates WHERE batch_id=? AND normalized_url=? LIMIT 1").bind(job.batchId,normalized).first();if(exists)continue;const candidateId=id("CC");await env.DB.prepare("INSERT INTO collection_candidates (id,batch_id,term_id,source_id,url,normalized_url,thumbnail,estimated_type,priority,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,1,'CANDIDATA',?,?)").bind(candidateId,job.batchId,term.id,source.id,candidate.url,normalized,candidate.thumbnail||null,term.kind||null,ts,ts).run();unique++;termAdded++;discovered++;pushItems.push({url:candidate.url,universe:clean(term.universe)||undefined,subject:clean(term.term),tags:["auto-collection",job.batchId,clean(term.id),clean(source.id)]});}
          let opId:string|null=null;if(pushItems.length){const push=await enqueueFastPushItems(env,pushItems,{type:"AUTO_COLLECTION"});if("operationId" in push){opId=clean(push.operationId)||null;materializeOps++;for(const candidate of q.items){await env.DB.prepare("UPDATE collection_candidates SET materialization_batch_id=? WHERE batch_id=? AND normalized_url=? AND materialization_batch_id IS NULL").bind(opId,job.batchId,normalizedUrl(candidate.url)).run();}}}
          await env.DB.batch([env.DB.prepare("INSERT INTO collection_source_runs (id,batch_id,term_id,source_id,found_count,unique_count,materialized_count,failure_count,duration_ms,status,detail,created_at) VALUES (?,?,?,?,?,?,?,0,?,'OK',?,?)").bind(runId,job.batchId,term.id,source.id,q.items.length,unique,pushItems.length,q.durationMs,opId?`operation=${opId}`:null,ts),env.DB.prepare("UPDATE collection_sources SET query_count=query_count+1,found_count=found_count+?,unique_count=unique_count+?,materialized_count=materialized_count+?,total_duration_ms=total_duration_ms+?,updated_at=? WHERE id=?").bind(q.items.length,unique,pushItems.length,q.durationMs,ts,source.id)]);await event(env,job.batchId,"SOURCE_RUN","OK",{found:q.items.length,unique,materializationOperation:opId},clean(term.id),clean(source.id));
        }catch(error){failed++;const msg=error instanceof Error?error.message:String(error);await env.DB.batch([env.DB.prepare("INSERT INTO collection_source_runs (id,batch_id,term_id,source_id,found_count,unique_count,materialized_count,failure_count,duration_ms,status,detail,created_at) VALUES (?,?,?,?,0,0,0,1,0,'FAILED',?,?)").bind(runId,job.batchId,term.id,source.id,msg,ts),env.DB.prepare("UPDATE collection_sources SET query_count=query_count+1,failure_count=failure_count+1,updated_at=? WHERE id=?").bind(ts,source.id)]);await event(env,job.batchId,"SOURCE_RUN","FAILED",{error:msg},clean(term.id),clean(source.id));}}
      await env.DB.prepare("UPDATE collection_terms SET rounds=rounds+1,attempts=attempts+1,updated_at=? WHERE id=?").bind(nowMs(),term.id).run();}
    const current=await env.DB.prepare("SELECT COUNT(*) AS n FROM collection_candidates WHERE term_id=?").bind(term.id).first<{n:number}>(),count=Number(current?.n||0),done=count>=Number(term.target_quantity||0);await env.DB.prepare("UPDATE collection_terms SET collected_count=?,status=?,failure_reason=?,updated_at=? WHERE id=?").bind(count,done?"CONCLUIDO":"PENDENTE",done?null:(sources.results?.length?null:"NO_ACTIVE_SOURCES"),nowMs(),term.id).run();}
  const aggregate=await env.DB.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='CONCLUIDO' THEN 1 ELSE 0 END) AS done FROM collection_terms WHERE batch_id=?").bind(job.batchId).first<{total:number;done:number}>(),count=await env.DB.prepare("SELECT COUNT(*) AS n FROM collection_candidates WHERE batch_id=?").bind(job.batchId).first<{n:number}>(),complete=Number(aggregate?.done||0)>=Number(aggregate?.total||0)&&Number(aggregate?.total||0)>0,doneTs=nowMs(),status=complete?"CONCLUIDO":"PARCIAL";await env.DB.batch([env.DB.prepare("UPDATE collection_batches SET status=?,total_collected=?,report_text=?,completed_at=CASE WHEN ? THEN ? ELSE completed_at END,updated_at=? WHERE id=?").bind(status,Number(count?.n||0),JSON.stringify({discovered,failed,materializeOps}),complete?1:0,doneTs,doneTs,job.batchId),env.DB.prepare("UPDATE v2_ingest_operations SET status='COMPLETED',succeeded=1,failed=?,updated_at=? WHERE id=?").bind(failed,doneTs,job.operationId),env.DB.prepare("UPDATE v2_control_jobs SET status='COMPLETED',result_json=?,updated_at=?,completed_at=? WHERE operation_id=? AND kind='COLLECTION_TICK'").bind(JSON.stringify({batchId:job.batchId,status,discovered,failed,materializeOps}),doneTs,doneTs,job.operationId)]);await event(env,job.batchId,"COLLECTION_TICK_COMPLETED",status,{discovered,failed,materializeOps});return{batchId:job.batchId,status,discovered,failed,materializeOps};}

export async function collectionStatus(env:Env,batchId:string){const batch=await env.DB.prepare("SELECT * FROM collection_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch)return null;const terms=await env.DB.prepare("SELECT * FROM collection_terms WHERE batch_id=? ORDER BY updated_at DESC").bind(batchId).all<Record<string,unknown>>(),runs=await env.DB.prepare("SELECT * FROM collection_source_runs WHERE batch_id=? ORDER BY created_at DESC LIMIT 100").bind(batchId).all<Record<string,unknown>>(),events=await env.DB.prepare("SELECT * FROM v2_collection_events WHERE batch_id=? ORDER BY created_at DESC LIMIT 100").bind(batchId).all<Record<string,unknown>>();return{batch,terms:terms.results||[],recentRuns:runs.results||[],events:events.results||[]};}
export async function listCollectionBatches(env:Env,limit=50){const rows=await env.DB.prepare("SELECT * FROM collection_batches ORDER BY created_at DESC LIMIT ?").bind(Math.max(1,Math.min(limit,200))).all<Record<string,unknown>>();return{items:rows.results||[]};}
export async function controlCollectionBatch(env:Env,batchId:string,action:"PAUSE"|"RESUME"|"CANCEL"){const row=await env.DB.prepare("SELECT * FROM collection_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!row)return null;const ts=nowMs();if(action==="CANCEL")await env.DB.prepare("UPDATE collection_batches SET status='CANCELADO',cancelled=1,completed_at=?,updated_at=? WHERE id=?").bind(ts,ts,batchId).run();else if(action==="PAUSE")await env.DB.prepare("UPDATE collection_batches SET status='PAUSADO',updated_at=? WHERE id=?").bind(ts,batchId).run();else await env.DB.prepare("UPDATE collection_batches SET status='CRIADO',cancelled=0,updated_at=? WHERE id=?").bind(ts,batchId).run();await event(env,batchId,`BATCH_${action}`,action,{});return{batchId,action};}
export async function collectionReport(env:Env,batchId:string){const s=await collectionStatus(env,batchId);if(!s)return null;const failures=(s.recentRuns as Record<string,unknown>[]).filter(r=>r.status==="FAILED");return{batch:s.batch,terms:s.terms,failures,totalFailures:failures.length,report:(s.batch as Record<string,unknown>).report_text};}
export async function collectionAnalysis(env:Env,batchId:string){const rows=await env.DB.prepare("SELECT source_id,status,COUNT(*) AS n FROM collection_candidates WHERE batch_id=? GROUP BY source_id,status ORDER BY n DESC").bind(batchId).all<Record<string,unknown>>(),dup=await env.DB.prepare("SELECT normalized_url,COUNT(*) AS n FROM collection_candidates WHERE batch_id=? GROUP BY normalized_url HAVING COUNT(*)>1 LIMIT 100").bind(batchId).all<Record<string,unknown>>();return{bySourceStatus:rows.results||[],duplicates:dup.results||[]};}
