import type { Env } from "../types";
import { createSignedCandidateUrl, createSignedFileUrl } from "./auth";
import { approveCandidate, enqueueFastPushItems, rejectCandidate } from "./ingest";
import { id, nowMs } from "./ids";

function clean(v:unknown){return String(v??"").trim();}
function tags(v:unknown){return Array.isArray(v)?[...new Set(v.map(String).map(clean).filter(Boolean))]:[];}
function asCandidateRows(item:Record<string,unknown>){const rows=Array.isArray(item.candidatas)?item.candidatas as Array<Record<string,unknown>>:[];return rows.filter(r=>/^https?:\/\//i.test(clean(r.url))).slice(0,5);}

type MaterializationItemInput={
  item_id:string; arquivo_alvo?:string; conceito?:string; referencia_visual?:string; universo?:string; preset?:string; slot?:string; tipo?:string; sujeito?:string; tags?:string[]; referencia_roteiro?:string; usado_para?:string; min_width?:number; min_height?:number; transparencia_necessaria?:boolean; candidatas?:Array<{priority?:number;url:string;source?:string}>;
};

async function batchProjectId(env:Env,batchId:string){const row=await env.DB.prepare("SELECT project FROM materialization_batches WHERE id=?").bind(batchId).first<{project:string}>();if(!row)return null;const byId=await env.DB.prepare("SELECT id FROM automatic_projects WHERE id=?").bind(row.project).first<{id:string}>();if(byId)return byId.id;const byName=await env.DB.prepare("SELECT id FROM automatic_projects WHERE name=? ORDER BY created_at DESC LIMIT 1").bind(row.project).first<{id:string}>();return byName?.id||null;}
async function findItem(env:Env,batchId:string,itemId:string){return env.DB.prepare("SELECT * FROM materialization_items WHERE batch_id=? AND item_id=? ORDER BY created_at DESC LIMIT 1").bind(batchId,itemId).first<Record<string,unknown>>();}

async function insertItemsAndQueue(env:Env,batchId:string,project:string,items:MaterializationItemInput[]){
  const ts=nowMs(), statements=[] as D1PreparedStatement[], push:Array<{url:string;projectId?:string;itemId?:string;universe?:string;subject?:string;tags?:string[]}>=[];
  const projectId=await batchProjectId(env,batchId) || (await env.DB.prepare("SELECT id FROM automatic_projects WHERE id=? OR name=? ORDER BY created_at DESC LIMIT 1").bind(project,project).first<{id:string}>())?.id;
  let added=0,candidateCount=0;
  for(const raw of items.slice(0,40)){
    const itemId=clean(raw.item_id);if(!itemId)continue;
    const existing=await findItem(env,batchId,itemId);if(existing)continue;
    const dbId=id("MIT");
    statements.push(env.DB.prepare(`INSERT INTO materialization_items (id,batch_id,item_id,target_name,concept,visual_reference,universe,preset,slot,kind,subject,tags,script_reference,used_for,min_width,min_height,status,candidate_cursor,route_class,created_at,updated_at,requires_alpha,composition_class) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'QUEUED',0,'V2_QUEUE',?,?,?,?,?)`)
      .bind(dbId,batchId,itemId,clean(raw.arquivo_alvo)||`${itemId}.bin`,clean(raw.conceito)||itemId,clean(raw.referencia_visual)||null,clean(raw.universo)||null,clean(raw.preset)||null,clean(raw.slot)||null,clean(raw.tipo)||null,clean(raw.sujeito)||null,JSON.stringify(tags(raw.tags)),clean(raw.referencia_roteiro)||null,clean(raw.usado_para)||null,Math.max(1,Number(raw.min_width||64)),Math.max(1,Number(raw.min_height||64)),ts,ts,raw.transparencia_necessaria?1:0,raw.transparencia_necessaria?"ISOLATED":"CONTEXTUAL"));
    const candidates=asCandidateRows(raw as unknown as Record<string,unknown>);
    for(let i=0;i<candidates.length;i++){
      const c=candidates[i],cid=id("MCAND"),url=clean(c.url);let host:string|null=null;try{host=new URL(url).hostname.toLowerCase();}catch{}
      statements.push(env.DB.prepare("INSERT INTO materialization_candidates (id,item_db_id,priority,source,original_url,host,adapter,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'v2-fast-push','QUEUED',?,?)").bind(cid,dbId,Number(c.priority||i+1),clean(c.source)||null,url,host,ts,ts));
      push.push({url,projectId:projectId||undefined,itemId,universe:clean(raw.universo)||undefined,subject:clean(raw.sujeito)||undefined,tags:tags(raw.tags)});candidateCount++;
    }
    added++;
  }
  if(statements.length)await env.DB.batch(statements);
  await env.DB.prepare("UPDATE materialization_batches SET total_items=(SELECT COUNT(*) FROM materialization_items WHERE batch_id=?),status=CASE WHEN cancelled=1 THEN status ELSE 'RUNNING' END,updated_at=? WHERE id=?").bind(batchId,ts,batchId).run();
  const pushed=push.length?await enqueueFastPushItems(env,push,{type:"MATERIALIZATION_BATCH"}):null;
  return{batch_id:batchId,items_added:added,candidates_queued:candidateCount,operation_id:pushed&&!("error" in pushed)?pushed.operationId:null,project_id:projectId||null};
}

export async function createContinuousMaterializationQueue(env:Env,input:{batchId?:string;project:string}){
  const batchId=clean(input.batchId)||id("MATB");const current=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(current)return{...current,idempotent:true};const ts=nowMs();await env.DB.prepare("INSERT INTO materialization_batches (id,project,status,total_items,completed_items,failed_items,cancelled,created_at,updated_at) VALUES (?,?,'QUEUE_OPEN',0,0,0,0,?,?)").bind(batchId,input.project,ts,ts).run();return env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();
}
export async function materializeBatchCompat(env:Env,input:{batchId?:string;project:string;items:MaterializationItemInput[]}){const batchId=clean(input.batchId)||id("MATB");let batch=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch){const ts=nowMs();await env.DB.prepare("INSERT INTO materialization_batches (id,project,status,total_items,completed_items,failed_items,cancelled,created_at,updated_at) VALUES (?,?,'BATCH_CREATED',0,0,0,0,?,?)").bind(batchId,input.project,ts,ts).run();}else if(Number(batch.cancelled||0))return{error:"BATCH_CANCELLED",status:409};return insertItemsAndQueue(env,batchId,input.project,input.items||[]);}
export async function addMaterializationItems(env:Env,batchId:string,items:MaterializationItemInput[]){const batch=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch)return{error:"BATCH_NOT_FOUND",status:404}as const;if(Number(batch.cancelled||0))return{error:"BATCH_CANCELLED",status:409}as const;return insertItemsAndQueue(env,batchId,clean(batch.project),items);}

export async function getMaterializationBatchStatus(env:Env,batchId:string){const batch=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch)return null;const items=await env.DB.prepare("SELECT * FROM materialization_items WHERE batch_id=? ORDER BY created_at").bind(batchId).all<Record<string,unknown>>();const enriched=[] as Record<string,unknown>[];for(const item of items.results||[]){const c=await env.DB.prepare("SELECT id,status,r2_key,asset_id,mime_type,size_bytes,failure_reason,attempts,updated_at FROM v2_ingest_candidates WHERE item_id=? ORDER BY updated_at DESC LIMIT 10").bind(item.item_id).all<Record<string,unknown>>();enriched.push({...item,candidates:c.results||[]});}return{...batch,items:enriched};}
export async function getMaterializationItemStatus(env:Env,input:{batchId?:string;itemId?:string;materializationId?:string}){let item:Record<string,unknown>|null=null;if(input.batchId&&input.itemId)item=await findItem(env,input.batchId,input.itemId);else if(input.materializationId)item=await env.DB.prepare("SELECT mi.* FROM materialization_items mi LEFT JOIN materialization_files mf ON mf.item_db_id=mi.id WHERE mf.id=? OR mi.id=? LIMIT 1").bind(input.materializationId,input.materializationId).first<Record<string,unknown>>();if(!item)return null;const candidates=await env.DB.prepare("SELECT * FROM v2_ingest_candidates WHERE item_id=? ORDER BY updated_at DESC LIMIT 20").bind(item.item_id).all<Record<string,unknown>>();return{...item,candidates:candidates.results||[]};}

export async function addCandidatesToMaterializationItem(env:Env,input:{batchId:string;itemId:string;candidates:Array<{priority?:number;url:string;source?:string}>}){const item=await findItem(env,input.batchId,input.itemId);if(!item)return{error:"ITEM_NOT_FOUND",status:404}as const;const rows=(input.candidates||[]).filter(c=>/^https?:\/\//i.test(clean(c.url))).slice(0,20),ts=nowMs(),stmts=[] as D1PreparedStatement[];for(let i=0;i<rows.length;i++){const c=rows[i],url=clean(c.url);let host:string|null=null;try{host=new URL(url).hostname.toLowerCase();}catch{}stmts.push(env.DB.prepare("INSERT INTO materialization_candidates (id,item_db_id,priority,source,original_url,host,adapter,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'v2-fast-push','QUEUED',?,?)").bind(id("MCAND"),item.id,Number(c.priority||i+1),clean(c.source)||null,url,host,ts,ts));}if(stmts.length)await env.DB.batch(stmts);const projectId=await batchProjectId(env,input.batchId);const pushed=rows.length?await enqueueFastPushItems(env,rows.map(c=>({url:c.url,projectId:projectId||undefined,itemId:input.itemId,universe:clean(item.universe)||undefined,subject:clean(item.subject)||undefined,tags:JSON.parse(clean(item.tags)||"[]")})),{type:"MATERIALIZATION_CANDIDATES"}):null;await env.DB.prepare("UPDATE materialization_items SET status='RUNNING',failure_reason=NULL,updated_at=? WHERE id=?").bind(ts,item.id).run();return{batch_id:input.batchId,item_id:input.itemId,added:rows.length,operation_id:pushed&&!("error" in pushed)?pushed.operationId:null};}

export async function assetsForQa(request:Request,env:Env,batchId:string,limit=20){const items=await env.DB.prepare("SELECT * FROM materialization_items WHERE batch_id=? ORDER BY created_at LIMIT ?").bind(batchId,Math.max(1,Math.min(limit,100))).all<Record<string,unknown>>();const out=[] as Record<string,unknown>[];for(const item of items.results||[]){if(item.frozen_asset_id){out.push({...item,asset_id:item.frozen_asset_id,preview_url:await createSignedFileUrl(request,clean(item.frozen_asset_id),env,900)});continue;}const c=await env.DB.prepare("SELECT * FROM v2_ingest_candidates WHERE item_id=? AND status='MATERIALIZED' ORDER BY updated_at DESC LIMIT 1").bind(item.item_id).first<Record<string,unknown>>();out.push({...item,candidate_id:c?.id||null,preview_url:c?.r2_key?await createSignedCandidateUrl(request,clean(c.id),env,900):null,mime_type:c?.mime_type||null,size_bytes:Number(c?.size_bytes||0),failure_reason:c?.failure_reason||null});}return{batch_id:batchId,mode:"LINKS_ONLY",items:out};}

export async function registerMaterializationQa(env:Env,batchId:string,decisions:Array<{item_id:string;status:string;observacao?:string}>){const results=[] as Record<string,unknown>[];for(const d of decisions.slice(0,100)){const item=await findItem(env,batchId,d.item_id);if(!item){results.push({item_id:d.item_id,error:"ITEM_NOT_FOUND"});continue;}const status=clean(d.status).toUpperCase();if(["APROVADO","APPROVED"].includes(status)){let c=await env.DB.prepare("SELECT * FROM v2_ingest_candidates WHERE item_id=? AND status='MATERIALIZED' ORDER BY updated_at DESC LIMIT 1").bind(d.item_id).first<Record<string,unknown>>();if(!c&&item.frozen_asset_id){results.push({item_id:d.item_id,asset_id:item.frozen_asset_id,idempotent:true});continue;}if(!c){results.push({item_id:d.item_id,error:"NO_MATERIALIZED_CANDIDATE"});continue;}const ap=await approveCandidate(clean(c.id),env);if("error" in ap){results.push({item_id:d.item_id,error:ap.error});continue;}await env.DB.prepare("UPDATE materialization_items SET status='FROZEN',selected_candidate_id=?,frozen_asset_id=?,failure_reason=NULL,updated_at=? WHERE id=?").bind(c.id,ap.assetId,nowMs(),item.id).run();results.push({item_id:d.item_id,status:"FROZEN",asset_id:ap.assetId});}
    else if(["REJEITADO","REJECTED"].includes(status)){const cs=await env.DB.prepare("SELECT id,status FROM v2_ingest_candidates WHERE item_id=? AND status IN ('MATERIALIZED','QUEUED','FAILED','RETRYING') ORDER BY updated_at DESC LIMIT 20").bind(d.item_id).all<Record<string,unknown>>();for(const c of cs.results||[]){if(clean(c.status)==="MATERIALIZED")await rejectCandidate(clean(c.id),env);else await env.DB.prepare("UPDATE v2_ingest_candidates SET status='REJECTED',updated_at=? WHERE id=?").bind(nowMs(),c.id).run();}await env.DB.prepare("UPDATE materialization_items SET status='REJECTED',failure_reason=?,updated_at=? WHERE id=?").bind(d.observacao||"QA_REJECTED",nowMs(),item.id).run();results.push({item_id:d.item_id,status:"REJECTED"});}
    else {await env.DB.prepare("UPDATE materialization_items SET status='QA_REVIEW',failure_reason=?,updated_at=? WHERE id=?").bind(d.observacao||status,nowMs(),item.id).run();results.push({item_id:d.item_id,status:"QA_REVIEW"});}}
  const agg=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='FROZEN' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status IN ('FAILED','REJECTED') THEN 1 ELSE 0 END) failed FROM materialization_items WHERE batch_id=?").bind(batchId).first<{total:number;completed:number;failed:number}>();await env.DB.prepare("UPDATE materialization_batches SET total_items=?,completed_items=?,failed_items=?,status=CASE WHEN ? >= ? AND ?>0 THEN 'COMPLETED' ELSE status END,updated_at=? WHERE id=?").bind(Number(agg?.total||0),Number(agg?.completed||0),Number(agg?.failed||0),Number(agg?.completed||0)+Number(agg?.failed||0),Number(agg?.total||0),Number(agg?.total||0),nowMs(),batchId).run();return{batch_id:batchId,results};}

export async function cancelMaterializationBatch(env:Env,batchId:string){const result=await env.DB.prepare("UPDATE materialization_batches SET cancelled=1,status='CANCELLED',updated_at=? WHERE id=?").bind(nowMs(),batchId).run();if(!Number(result.meta?.changes||0))return null;await env.DB.prepare("UPDATE materialization_items SET status=CASE WHEN status='FROZEN' THEN status ELSE 'CANCELLED' END,updated_at=? WHERE batch_id=?").bind(nowMs(),batchId).run();return getMaterializationBatchStatus(env,batchId);}
export async function cleanMaterializationTemporaries(env:Env,batchId:string,confirm:boolean){if(!confirm)return{error:"CONFIRM_REQUIRED",status:400}as const;const batch=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch)return{error:"BATCH_NOT_FOUND",status:404}as const;if(!["COMPLETED","CANCELLED","FAILED"].includes(clean(batch.status).toUpperCase()))return{error:"BATCH_NOT_TERMINAL",currentStatus:batch.status,status:409}as const;const ids=await env.DB.prepare("SELECT item_id FROM materialization_items WHERE batch_id=?").bind(batchId).all<{item_id:string}>();let deleted=0;for(const i of ids.results||[]){const rows=await env.DB.prepare("SELECT id,r2_key,status FROM v2_ingest_candidates WHERE item_id=? AND status NOT IN ('APPROVED')").bind(i.item_id).all<{id:string;r2_key:string|null;status:string}>();for(const r of rows.results||[]){if(r.r2_key){await env.MEDIA.delete(r.r2_key).catch(()=>undefined);deleted++;}await env.DB.prepare("UPDATE v2_ingest_candidates SET r2_key=NULL,status=CASE WHEN status='MATERIALIZED' THEN 'CLEANED' ELSE status END,updated_at=? WHERE id=?").bind(nowMs(),r.id).run();}}return{batch_id:batchId,deleted_objects:deleted};}

export async function applyTechnicalCorrectionCompat(env:Env,input:{batchId:string;itemId:string;urlResult?:string;operations?:string[];parameters?:unknown}){const item=await findItem(env,input.batchId,input.itemId);if(!item)return{error:"ITEM_NOT_FOUND",status:404}as const;const ops=(input.operations||[]).map(clean).filter(Boolean);if(!clean(input.urlResult))return{error:"TRANSFORM_SERVICE_REQUIRED",status:501,reason:"A V2 não executa transformação semântica/visual dentro do Worker. Informe url_resultado de um processador técnico externo; a linhagem continuará preservada.",allowed_operations:ops};const result=await addCandidatesToMaterializationItem(env,{batchId:input.batchId,itemId:input.itemId,candidates:[{url:clean(input.urlResult),source:"technical-correction"}]});await env.DB.prepare("UPDATE materialization_items SET failure_reason=?,updated_at=? WHERE id=?").bind(JSON.stringify({technical_operations:ops,technical_parameters:input.parameters||{}}),nowMs(),item.id).run();return{...result,technical:true};}

export async function materializationLog(env:Env,batchId:string,itemId?:string){const batch=await env.DB.prepare("SELECT * FROM materialization_batches WHERE id=?").bind(batchId).first<Record<string,unknown>>();if(!batch)return null;const items=itemId?[await findItem(env,batchId,itemId)].filter(Boolean) as Record<string,unknown>[]:(await env.DB.prepare("SELECT * FROM materialization_items WHERE batch_id=? ORDER BY updated_at DESC").bind(batchId).all<Record<string,unknown>>()).results||[];const events=[] as Record<string,unknown>[];for(const item of items){const rows=await env.DB.prepare("SELECT e.* FROM v2_ingest_events e JOIN v2_ingest_candidates c ON c.id=e.candidate_id WHERE c.item_id=? ORDER BY e.created_at DESC LIMIT 100").bind(item.item_id).all<Record<string,unknown>>();events.push(...rows.results||[]);}return{batch,items,events:events.sort((a,b)=>Number(b.created_at||0)-Number(a.created_at||0)).slice(0,500)};}
