import type { Env } from "../types";
import { id, nowMs } from "./ids";

const RULE_TYPE="PERSISTENT_CONTEXT_POLICY";
const CATEGORY="OPERATIONAL_CONTEXT";
const SCOPES=new Set(["GLOBAL","PRESET","PROJECT","SLOT"]);
const clean=(value:unknown)=>String(value??"").trim();
const upper=(value:unknown)=>clean(value).toUpperCase();
const parseJson=(value:unknown,fallback:Record<string,unknown>={})=>{try{return JSON.parse(String(value??"")) as Record<string,unknown>}catch{return fallback}};

function scopeRank(scope:string,linked=false){if(linked)return 300;return scope==="SLOT"?400:scope==="PROJECT"?300:scope==="PRESET"?200:100;}
function splitSlotTarget(targetId:string){const value=clean(targetId);const idx=value.indexOf(":");return idx>0?{projectId:value.slice(0,idx),slotId:value.slice(idx+1)}:{projectId:"",slotId:value};}
function targetFromRow(row:Record<string,unknown>){const scope=upper(row.scope_level);const condition=parseJson(row.condition_json);if(scope==="PRESET")return clean(row.preset);if(scope==="PROJECT")return clean(row.project_id);if(scope==="SLOT")return clean(condition.target_id)||[clean(row.project_id),clean(condition.slot_id)].filter(Boolean).join(":");return "GLOBAL";}
function instructionFromRow(row:Record<string,unknown>){const action=parseJson(row.action_json);return clean(action.instruction)||clean(row.description);}
function normalizeRow(row:Record<string,unknown>,linked=false){
  const action=parseJson(row.action_json),condition=parseJson(row.condition_json),scope=upper(row.scope_level)||"GLOBAL";
  return {
    id:row.id,policy_id:row.id,policy_key:row.policy_key,title:row.name,description:row.description||null,scope,target_id:targetFromRow(row),
    instruction:instructionFromRow(row),priority:Number(row.priority||1),active:upper(row.status)==="ACTIVE",status:row.status,created_by:row.created_by,
    created_at:row.created_at,updated_at:row.updated_at,version:Number(row.version||1),previous_version_id:row.previous_version_id||null,
    metadata:(action.metadata&&typeof action.metadata==="object")?action.metadata:{},asset_requirement:action.asset_requirement||null,asset_requirements:action.asset_requirements||null,
    applies_to:Array.isArray(action.applies_to)?action.applies_to:[],slot_id:condition.slot_id||null,preset:row.preset||null,project_id:row.project_id||null,
    linked_to_project:linked,effective_rank:scopeRank(scope,linked),
  };
}
async function touchPolicyRevision(env:Env,projectId?:string){const ts=nowMs();await env.DB.prepare("INSERT OR REPLACE INTO v2_schema_meta(key,value,updated_at) VALUES ('operational_policy_revision',?,?)").bind(String(ts),ts).run().catch(()=>undefined);if(projectId)await env.DB.prepare("UPDATE automatic_projects SET state_version=state_version+1,workflow_updated_at=?,updated_at=? WHERE id=?").bind(ts,ts,projectId).run().catch(()=>undefined);}
async function touchLinkedProjects(env:Env,policyId:string,ts=nowMs()){const rows=await env.DB.prepare("SELECT DISTINCT project_id FROM v2_project_policy_links WHERE policy_id=? AND active=1").bind(policyId).all<{project_id:string}>().catch(()=>({results:[]} as unknown as D1Result<{project_id:string}>));for(const row of rows.results||[])await env.DB.prepare("UPDATE automatic_projects SET state_version=state_version+1,workflow_updated_at=?,updated_at=? WHERE id=?").bind(ts,ts,row.project_id).run().catch(()=>undefined);}

export async function createPersistentPolicy(env:Env,input:{policyKey:string;title:string;description?:string;scope:string;targetId?:string;instruction:string;priority?:number;metadata?:Record<string,unknown>;assetRequirement?:string;assetRequirements?:Record<string,string>;appliesTo?:string[];createdBy?:string;active?:boolean}){
  const policyKey=clean(input.policyKey);const title=clean(input.title);const instruction=clean(input.instruction);const scope=upper(input.scope);if(!policyKey||!title||!instruction)return {error:"POLICY_KEY_TITLE_INSTRUCTION_REQUIRED",status:400} as const;if(!SCOPES.has(scope))return {error:"INVALID_POLICY_SCOPE",allowed:[...SCOPES],status:400} as const;
  const existing=await env.DB.prepare("SELECT * FROM operational_policies WHERE policy_key=? AND rule_type=? AND status NOT IN ('DELETED','SUPERSEDED') ORDER BY version DESC,updated_at DESC LIMIT 1").bind(policyKey,RULE_TYPE).first<Record<string,unknown>>();if(existing)return {policy:normalizeRow(existing),idempotent:true};
  const targetId=clean(input.targetId);let preset:string|null=null,projectId:string|null=null,slotId:string|null=null;if(scope!=="GLOBAL"&&!targetId)return {error:"TARGET_ID_REQUIRED",scope,status:400} as const;if(scope==="PRESET")preset=targetId;if(scope==="PROJECT")projectId=targetId;if(scope==="SLOT"){const parsed=splitSlotTarget(targetId);projectId=parsed.projectId;slotId=parsed.slotId;if(!projectId||!slotId)return {error:"SLOT_TARGET_MUST_BE_PROJECT_COLON_SLOT",status:400} as const;}
  const ts=nowMs(),policyId=id("POL"),status=input.active===false?"SUSPENDED":"ACTIVE";const action={instruction,metadata:input.metadata||{},asset_requirement:clean(input.assetRequirement)||undefined,asset_requirements:input.assetRequirements||undefined,applies_to:input.appliesTo||undefined};const condition={target_id:scope==="GLOBAL"?"GLOBAL":targetId,slot_id:slotId||undefined};
  await env.DB.prepare(`INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,project_id,item_id,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?,?)`).bind(policyId,policyKey,title,clean(input.description)||null,CATEGORY,status,RULE_TYPE,scope,scopeRank(scope),preset,projectId,null,JSON.stringify(condition),JSON.stringify(action),Math.max(1,Number(input.priority||50)),100,clean(input.createdBy)||"SUPERVISOR_MCP","Persistent operational context policy",ts,ts).run();
  await touchPolicyRevision(env,projectId||undefined);const row=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();return {policy:row?normalizeRow(row):null,idempotent:false};
}

export async function editPersistentPolicy(env:Env,policyId:string,input:{title?:string;description?:string;scope?:string;targetId?:string;instruction?:string;priority?:number;metadata?:Record<string,unknown>;assetRequirement?:string|null;assetRequirements?:Record<string,string>|null;appliesTo?:string[];createdBy?:string}){
  const current=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=? AND rule_type=?").bind(clean(policyId),RULE_TYPE).first<Record<string,unknown>>();if(!current)return {error:"POLICY_NOT_FOUND",status:404} as const;
  const currentNorm=normalizeRow(current);const scope=upper(input.scope??current.scope_level);if(!SCOPES.has(scope))return {error:"INVALID_POLICY_SCOPE",allowed:[...SCOPES],status:400} as const;const targetId=clean(input.targetId??targetFromRow(current));let preset:string|null=null,projectId:string|null=null,slotId:string|null=null;if(scope==="PRESET")preset=targetId;if(scope==="PROJECT")projectId=targetId;if(scope==="SLOT"){const parsed=splitSlotTarget(targetId);projectId=parsed.projectId;slotId=parsed.slotId;if(!projectId||!slotId)return {error:"SLOT_TARGET_MUST_BE_PROJECT_COLON_SLOT",status:400} as const;}
  const oldAction=parseJson(current.action_json);const action={...oldAction,instruction:clean(input.instruction??oldAction.instruction??current.description),metadata:input.metadata??oldAction.metadata??{},asset_requirement:input.assetRequirement===null?undefined:(input.assetRequirement??oldAction.asset_requirement),asset_requirements:input.assetRequirements===null?undefined:(input.assetRequirements??oldAction.asset_requirements),applies_to:input.appliesTo??oldAction.applies_to};const ts=nowMs(),nextId=id("POL"),version=Number(current.version||1)+1;
  const linkedProjects=await env.DB.prepare("SELECT DISTINCT project_id FROM v2_project_policy_links WHERE policy_id=? AND active=1").bind(current.id).all<{project_id:string}>().catch(()=>({results:[]} as unknown as D1Result<{project_id:string}>));
  await env.DB.batch([
    env.DB.prepare(`INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,project_id,item_id,condition_json,action_json,priority,confidence,created_by,version,previous_version_id,notes,created_at,updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(nextId,current.policy_key,clean(input.title??current.name),input.description===undefined?current.description:(clean(input.description)||null),CATEGORY,current.status,RULE_TYPE,scope,scopeRank(scope),preset,projectId,null,JSON.stringify({target_id:scope==="GLOBAL"?"GLOBAL":targetId,slot_id:slotId||undefined}),JSON.stringify(action),Math.max(1,Number(input.priority??current.priority??50)),100,clean(input.createdBy)||"SUPERVISOR_MCP",version,current.id,"Persistent operational context policy version",ts,ts),
    env.DB.prepare("UPDATE operational_policies SET status='SUPERSEDED',updated_at=? WHERE id=?").bind(ts,current.id),
  ]);
  await env.DB.prepare("UPDATE v2_project_policy_links SET policy_id=?,updated_at=? WHERE policy_id=?").bind(nextId,ts,current.id).run().catch(()=>undefined);
  await touchPolicyRevision(env,projectId||clean(currentNorm.project_id)||undefined);for(const linked of linkedProjects.results||[])await env.DB.prepare("UPDATE automatic_projects SET state_version=state_version+1,workflow_updated_at=?,updated_at=? WHERE id=?").bind(ts,ts,linked.project_id).run().catch(()=>undefined);const row=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(nextId).first<Record<string,unknown>>();return {policy:row?normalizeRow(row):null,superseded_policy_id:current.id};
}

export async function setPersistentPolicyActive(env:Env,policyId:string,active:boolean){const row=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=? AND rule_type=?").bind(clean(policyId),RULE_TYPE).first<Record<string,unknown>>();if(!row)return {error:"POLICY_NOT_FOUND",status:404} as const;const next=active?"ACTIVE":"SUSPENDED",ts=nowMs();if(upper(row.status)!==next)await env.DB.prepare("UPDATE operational_policies SET status=?,updated_at=? WHERE id=?").bind(next,ts,row.id).run();await touchPolicyRevision(env,clean(row.project_id)||undefined);await touchLinkedProjects(env,String(row.id),ts);const out=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(row.id).first<Record<string,unknown>>();return {policy:out?normalizeRow(out):null,idempotent:upper(row.status)===next};}
export async function removePersistentPolicy(env:Env,policyId:string){const row=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=? AND rule_type=?").bind(clean(policyId),RULE_TYPE).first<Record<string,unknown>>();if(!row)return {removed:false,idempotent:true};const ts=nowMs();await touchLinkedProjects(env,String(row.id),ts);if(upper(row.status)!=="DELETED")await env.DB.prepare("UPDATE operational_policies SET status='DELETED',updated_at=? WHERE id=?").bind(ts,row.id).run();await env.DB.prepare("UPDATE v2_project_policy_links SET active=0,removed_at=?,updated_at=? WHERE policy_id=? AND active=1").bind(ts,ts,row.id).run().catch(()=>undefined);await touchPolicyRevision(env,clean(row.project_id)||undefined);return {removed:true,policy_id:row.id,idempotent:upper(row.status)==="DELETED"};}

export async function listPersistentPolicies(env:Env,input:{scope?:string;targetId?:string;active?:boolean;policyKey?:string;limit?:number}={}){const where=["rule_type=?","status!='SUPERSEDED'"];const values:unknown[]=[RULE_TYPE];if(input.scope){where.push("scope_level=?");values.push(upper(input.scope));}if(input.active!==undefined){where.push(input.active?"status='ACTIVE'":"status!='ACTIVE'");}if(input.policyKey){where.push("policy_key=?");values.push(clean(input.policyKey));}if(input.targetId){const scope=upper(input.scope);if(scope==="PRESET"){where.push("preset=?");values.push(clean(input.targetId));}else if(scope==="PROJECT"){where.push("project_id=?");values.push(clean(input.targetId));}else if(scope==="SLOT"){const parsed=splitSlotTarget(input.targetId);where.push("project_id=? AND json_extract(condition_json,'$.slot_id')=?");values.push(parsed.projectId,parsed.slotId);}else{where.push("(preset=? OR project_id=? OR json_extract(condition_json,'$.target_id')=?)");values.push(clean(input.targetId),clean(input.targetId),clean(input.targetId));}}
  values.push(Math.max(1,Math.min(Number(input.limit||200),500)));const rows=await env.DB.prepare(`SELECT * FROM operational_policies WHERE ${where.join(" AND ")} ORDER BY CASE scope_level WHEN 'SLOT' THEN 4 WHEN 'PROJECT' THEN 3 WHEN 'PRESET' THEN 2 ELSE 1 END DESC,priority DESC,updated_at DESC LIMIT ?`).bind(...values).all<Record<string,unknown>>();return (rows.results||[]).map(row=>normalizeRow(row));}

export async function applyPersistentPolicyToProject(env:Env,input:{projectId:string;policyId:string;createdBy?:string}){const [project,policy]=await Promise.all([env.DB.prepare("SELECT id FROM automatic_projects WHERE id=?").bind(clean(input.projectId)).first(),env.DB.prepare("SELECT * FROM operational_policies WHERE id=? AND rule_type=? AND status!='DELETED'").bind(clean(input.policyId),RULE_TYPE).first<Record<string,unknown>>()]);if(!project)return {error:"PROJECT_NOT_FOUND",status:404} as const;if(!policy)return {error:"POLICY_NOT_FOUND",status:404} as const;const ts=nowMs(),linkId=id("PPL");const existing=await env.DB.prepare("SELECT * FROM v2_project_policy_links WHERE project_id=? AND policy_id=? LIMIT 1").bind(input.projectId,input.policyId).first<Record<string,unknown>>();if(existing){if(Number(existing.active||0)!==1)await env.DB.prepare("UPDATE v2_project_policy_links SET active=1,removed_at=NULL,created_by=?,updated_at=? WHERE id=?").bind(clean(input.createdBy)||"SUPERVISOR_MCP",ts,existing.id).run();await touchPolicyRevision(env,input.projectId);return {linked:true,idempotent:Number(existing.active||0)===1,link_id:existing.id,policy:normalizeRow(policy,true)};}
  await env.DB.prepare("INSERT INTO v2_project_policy_links(id,project_id,policy_id,active,created_by,created_at,updated_at) VALUES (?,?,?,1,?,?,?)").bind(linkId,input.projectId,input.policyId,clean(input.createdBy)||"SUPERVISOR_MCP",ts,ts).run();await touchPolicyRevision(env,input.projectId);return {linked:true,idempotent:false,link_id:linkId,policy:normalizeRow(policy,true)};}
export async function removePersistentPolicyFromProject(env:Env,input:{projectId:string;policyId:string}){const row=await env.DB.prepare("SELECT * FROM v2_project_policy_links WHERE project_id=? AND policy_id=? LIMIT 1").bind(clean(input.projectId),clean(input.policyId)).first<Record<string,unknown>>();if(!row)return {removed:false,idempotent:true};const ts=nowMs();if(Number(row.active||0)===1)await env.DB.prepare("UPDATE v2_project_policy_links SET active=0,removed_at=?,updated_at=? WHERE id=?").bind(ts,ts,row.id).run();await touchPolicyRevision(env,input.projectId);return {removed:true,idempotent:Number(row.active||0)!==1,link_id:row.id};}

export async function resolveApplicablePolicies(env:Env,input:{projectId:string;slotId?:string;preset?:string;visualRole?:string}){const projectId=clean(input.projectId),slotId=clean(input.slotId),preset=upper(input.preset),visualRole=upper(input.visualRole);const rows=await env.DB.prepare(`SELECT p.* FROM operational_policies p WHERE p.rule_type=? AND p.status='ACTIVE' AND (
    p.scope_level='GLOBAL' OR (p.scope_level='PRESET' AND upper(COALESCE(p.preset,''))=?) OR (p.scope_level='PROJECT' AND p.project_id=?) OR (p.scope_level='SLOT' AND p.project_id=? AND json_extract(p.condition_json,'$.slot_id')=?) OR p.id IN (SELECT policy_id FROM v2_project_policy_links WHERE project_id=? AND active=1)
  ) ORDER BY p.priority DESC,p.updated_at DESC`).bind(RULE_TYPE,preset,projectId,projectId,slotId,projectId).all<Record<string,unknown>>();const links=await env.DB.prepare("SELECT policy_id FROM v2_project_policy_links WHERE project_id=? AND active=1").bind(projectId).all<{policy_id:string}>().catch(()=>({results:[]} as unknown as D1Result<{policy_id:string}>));const linked=new Set((links.results||[]).map(row=>String(row.policy_id)));const normalized=(rows.results||[]).map(row=>normalizeRow(row,linked.has(String(row.id)))).filter((policy:any)=>{const applies=(policy.applies_to||[]).map((value:string)=>upper(value));return !visualRole||!applies.length||applies.includes(visualRole)||applies.includes(visualRole.replace(/^IMAGE/,"IMAGEM"));});normalized.sort((a:any,b:any)=>Number(b.effective_rank)-Number(a.effective_rank)||Number(b.priority)-Number(a.priority)||Number(b.version)-Number(a.version));const byKey=new Map<string,any>();for(const policy of normalized){const key=String(policy.policy_key);if(!byKey.has(key))byKey.set(key,policy);}const policies=[...byKey.values()];let assetRequirement:string|null=null;for(const policy of policies){const reqs=policy.asset_requirements as Record<string,string>|null;const direct=clean(policy.asset_requirement);const applies=(policy.applies_to||[]).map((value:string)=>upper(value));const roleCandidates=[visualRole,upper(slotId),upper(slotId.replace(/^SLOT-/i,""))].filter(Boolean);if(reqs){for(const role of roleCandidates){const exact=reqs[role]||reqs[role.replace(/^IMAGE/,"IMAGEM")];if(exact){assetRequirement=String(exact);break;}}if(assetRequirement)break;}if(direct){if(applies.length&&!roleCandidates.some(role=>applies.includes(role)||applies.includes(role.replace(/^IMAGE/,"IMAGEM"))))continue;assetRequirement=direct;break;}}
  const revision=await env.DB.prepare("SELECT value FROM v2_schema_meta WHERE key='operational_policy_revision'").first<{value:string}>().catch(()=>null);return {project_id:projectId,slot_id:slotId||null,visual_role:visualRole||null,preset:preset||null,policy_revision:revision?.value||null,asset_requirement:assetRequirement,policies};}

export async function listProjectPersistentPolicies(env:Env,projectId:string){const direct=await listPersistentPolicies(env,{scope:"PROJECT",targetId:projectId,limit:500});const links=await env.DB.prepare("SELECT l.*,p.* FROM v2_project_policy_links l JOIN operational_policies p ON p.id=l.policy_id WHERE l.project_id=? AND l.active=1 AND p.rule_type=? AND p.status!='DELETED' ORDER BY l.updated_at DESC").bind(clean(projectId),RULE_TYPE).all<Record<string,unknown>>().catch(()=>({results:[]} as unknown as D1Result<Record<string,unknown>>));return {project_id:projectId,direct,linked:(links.results||[]).map(row=>normalizeRow(row,true))};}
