import type { Env } from "../types";
import { enqueueSupervisorDecisions } from "./fast-control";
import { id, nowMs } from "./ids";

function clean(v:unknown){return String(v??"").trim();}
function parse<T>(v:unknown,fallback:T):T{try{return typeof v==="string"?JSON.parse(v) as T:(v as T??fallback)}catch{return fallback}}

async function project(env:Env,projectId:string){return env.DB.prepare("SELECT * FROM automatic_projects WHERE id=?").bind(projectId).first<Record<string,unknown>>();}

export async function createSupervisorPlan(env:Env,input:{projectId:string;operationId?:string;executionId?:string;intent?:string;scope?:unknown;maxParallelism?:number;stopConditions?:unknown;successConditions?:unknown;policies?:Record<string,unknown>;metadata?:unknown}){
  const p=await project(env,input.projectId);if(!p)return {error:"PROJECT_NOT_FOUND",status:404} as const;
  const operationId=clean(input.operationId)||id("OP"),existing=await env.DB.prepare("SELECT * FROM supervisor_plans WHERE operation_id=? LIMIT 1").bind(operationId).first<Record<string,unknown>>();if(existing)return {plan:existing,idempotent:true};
  const planId=id("PLAN"),ts=nowMs(),parallel=Math.max(1,Math.min(Number(input.maxParallelism||8),50)),policies=input.policies||{};
  await env.DB.prepare(`INSERT INTO supervisor_plans (id,project_id,execution_id,operation_id,idempotency_key,status,priority,intent,scope_json,max_parallelism,stop_conditions_json,success_conditions_json,fallback_policy_json,source_policy_json,qa_policy_json,relink_policy_json,technical_policy_json,metadata_json,result_summary_json,project_version_at_creation,policy_version,accepted_at,created_at,updated_at) VALUES (?,?,?,?,?,'ACCEPTED',1,?,?,?,?,?,?,?,?,?,?,?,'{}',?,'V2',?,?,?)`)
    .bind(planId,input.projectId,input.executionId||null,operationId,operationId,input.intent||"EXECUTE_UNTIL_DIVERGENCE",JSON.stringify(input.scope||{}),parallel,JSON.stringify(input.stopConditions||[]),JSON.stringify(input.successConditions||[]),JSON.stringify(policies.fallback||{}),JSON.stringify(policies.source||{}),JSON.stringify(policies.qa||{}),JSON.stringify(policies.relink||{}),JSON.stringify(policies.technical||{}),JSON.stringify(input.metadata||{}),Number(p.state_version||1),ts,ts,ts).run();
  const rows=await env.DB.prepare(`SELECT * FROM automatic_project_items WHERE project_id=? AND version=? AND upper(status) NOT IN ('FROZEN','APROVADO','APPROVED','CONCLUIDO','CONCLUÍDO','CANCELLED','CANCELADO') ORDER BY priority ASC,created_at ASC LIMIT 500`).bind(input.projectId,Number(p.active_version||1)).all<Record<string,unknown>>();
  const branches=[] as Record<string,unknown>[];let n=0;
  for(const item of rows.results||[]){const branchId=id("BR"),stage=clean(item.stage)||"DISCOVERY",ready=Number(item.stage_ready_at||ts),key=`${planId}:${clean(item.id)}:${stage}`;await env.DB.prepare("INSERT INTO plan_branches (id,plan_id,project_id,item_id,stage,branch_type,priority,status,ready_at,original_ready_at,worker_type,worker_domain,attempt,max_attempts,idempotency_key,payload_json,result_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'READY',?,?,?,?,0,3,?,'{}','{}',?,?)").bind(branchId,planId,input.projectId,item.id,stage,"PROJECT_ITEM",Number(item.priority||1),ready,Number(item.original_ready_at||ready),stage,clean(item.item_domain)||clean(p.project_domain)||"GENERAL",key,ts,ts).run();branches.push({id:branchId,itemId:item.id,stage,status:"READY"});if(++n>=parallel*8)break;}
  await env.DB.batch([env.DB.prepare("UPDATE supervisor_plans SET status='RUNNING',started_at=?,updated_at=? WHERE id=?").bind(ts,ts,planId),env.DB.prepare("UPDATE automatic_projects SET active_plan_id=?,pipeline_status='PROCESSANDO',next_action='EXECUTE_PLAN',state_version=state_version+1,updated_at=? WHERE id=?").bind(planId,ts,input.projectId)]);
  return {planId,operationId,projectId:input.projectId,status:"RUNNING",branchesCreated:branches.length,maxParallelism:parallel,branches,idempotent:false};
}

export async function getWorkPacket(env:Env,planId:string,limit=20){const plan=await env.DB.prepare("SELECT * FROM supervisor_plans WHERE id=?").bind(planId).first<Record<string,unknown>>();if(!plan)return null;const rows=await env.DB.prepare("SELECT * FROM plan_branches WHERE plan_id=? AND status IN ('READY','WAITING','FAILED') ORDER BY priority ASC,ready_at ASC LIMIT ?").bind(planId,Math.max(1,Math.min(limit,50))).all<Record<string,unknown>>();return{plan:{...plan,scope:parse(plan.scope_json,{}),metadata:parse(plan.metadata_json,{})},work:rows.results||[]};}
export async function getPlanStatus(env:Env,planId:string){const plan=await env.DB.prepare("SELECT * FROM supervisor_plans WHERE id=?").bind(planId).first<Record<string,unknown>>();if(!plan)return null;const c=await env.DB.prepare("SELECT status,COUNT(*) AS n FROM plan_branches WHERE plan_id=? GROUP BY status").bind(planId).all<{status:string;n:number}>();return{planId,status:plan.status,branches:Object.fromEntries((c.results||[]).map(r=>[r.status,Number(r.n)])),updatedAt:plan.updated_at};}
export async function getPlanDetails(env:Env,planId:string){const packet=await getWorkPacket(env,planId,50);if(!packet)return null;const all=await env.DB.prepare("SELECT * FROM plan_branches WHERE plan_id=? ORDER BY priority,created_at").bind(planId).all<Record<string,unknown>>();return{...packet,branches:all.results||[]};}
export async function getPlanExceptions(env:Env,planId:string,limit=100){const rows=await env.DB.prepare("SELECT * FROM plan_branches WHERE plan_id=? AND status IN ('FAILED','BLOCKED','DIVERGED','WAITING_SUPERVISOR') ORDER BY updated_at DESC LIMIT ?").bind(planId,Math.max(1,Math.min(limit,200))).all<Record<string,unknown>>();return{planId,exceptions:rows.results||[]};}

export async function setPlanStatus(env:Env,planId:string,status:"PAUSED"|"RUNNING"|"CANCELLED"){const row=await env.DB.prepare("SELECT * FROM supervisor_plans WHERE id=?").bind(planId).first<Record<string,unknown>>();if(!row)return null;const ts=nowMs(),complete=status==="CANCELLED"?ts:null;await env.DB.batch([env.DB.prepare("UPDATE supervisor_plans SET status=?,completed_at=COALESCE(?,completed_at),updated_at=? WHERE id=?").bind(status,complete,ts,planId),env.DB.prepare("UPDATE automatic_projects SET pipeline_status=?,next_action=?,updated_at=? WHERE id=?").bind(status==="RUNNING"?"PROCESSANDO":status,status==="RUNNING"?"EXECUTE_PLAN":null,ts,row.project_id)]);if(status==="CANCELLED")await env.DB.prepare("UPDATE plan_branches SET status='CANCELLED',finished_at=?,updated_at=? WHERE plan_id=? AND status NOT IN ('COMPLETED','CANCELLED')").bind(ts,ts,planId).run();return{planId,status};}

export async function tickPlans(env:Env,input:{planId?:string;limit?:number}={}){const values:unknown[]=[];let where="status='RUNNING'";if(input.planId){where+=" AND id=?";values.push(input.planId);}values.push(Math.max(1,Math.min(input.limit||20,100)));const plans=await env.DB.prepare(`SELECT * FROM supervisor_plans WHERE ${where} ORDER BY priority,updated_at LIMIT ?`).bind(...values).all<Record<string,unknown>>();const results=[];for(const plan of plans.results||[]){const stats=await getPlanStatus(env,clean(plan.id));const branches=stats?.branches||{};const pending=Object.entries(branches).filter(([k])=>!["COMPLETED","CANCELLED"].includes(k)).reduce((n,[,v])=>n+Number(v),0);if(pending===0){const ts=nowMs();await env.DB.batch([env.DB.prepare("UPDATE supervisor_plans SET status='COMPLETED',completed_at=?,updated_at=?,result_summary_json=? WHERE id=?").bind(ts,ts,JSON.stringify(stats),plan.id),env.DB.prepare("UPDATE automatic_projects SET active_plan_id=NULL,next_action=NULL,pipeline_status='PLANO_CONCLUIDO',updated_at=? WHERE id=? AND active_plan_id=?").bind(ts,plan.project_id,plan.id)]);results.push({planId:plan.id,status:"COMPLETED"});}else results.push({planId:plan.id,status:"RUNNING",pending});}return{processed:results.length,results};}

export async function supervisorExchange(env:Env,input:{projectId:string;operationId?:string;executionId?:string;intent?:string;decisions?:Array<{itemId:string;status:string;observation?:string}>;commands?:unknown[];scope?:unknown;policies?:Record<string,unknown>;maxParallelism?:number;packetLimit?:number}){
  let decisionsOperation:null|Record<string,unknown>=null;if(input.decisions?.length){const q=await enqueueSupervisorDecisions(env,{projectId:input.projectId,decisions:input.decisions,operationId:input.operationId?`${input.operationId}:decisions`:undefined});decisionsOperation=q as unknown as Record<string,unknown>;}
  const created=await createSupervisorPlan(env,{projectId:input.projectId,operationId:input.operationId,executionId:input.executionId,intent:input.intent,scope:input.scope,maxParallelism:input.maxParallelism,policies:input.policies,metadata:{commands:input.commands||[]}});if("error" in created)return created;
  const packet=await getWorkPacket(env,clean((created as Record<string,unknown>).planId||((created as Record<string,unknown>).plan as Record<string,unknown>)?.id),input.packetLimit||20);
  return{accepted:true,decisionsOperation,plan:created,workPacket:packet};
}

export async function executeUntilDivergence(env:Env,input:{projectId:string;operationId?:string;maxParallelism?:number;packetLimit?:number}){return supervisorExchange(env,{projectId:input.projectId,operationId:input.operationId,intent:"EXECUTE_UNTIL_DIVERGENCE",maxParallelism:input.maxParallelism,packetLimit:input.packetLimit});}

export async function createSourceRoutingPlan(env:Env,input:{projectId?:string;itemId?:string;collectionTermId?:string;universe?:string;compositionClass?:string;targetType?:string;canonicalReference?:string;eligibleSources?:string[];excludedSources?:string[];discoverySources?:string[];materializationSources?:string[];fallbackSources?:string[]}){const ts=nowMs(),routeId=id("ROUTE");let domain="GENERAL";if(input.projectId){const p=await project(env,input.projectId);if(p)domain=clean(p.project_domain)||domain;}await env.DB.prepare("INSERT INTO source_routing_plans (id,project_id,item_id,collection_term_id,project_domain,universe,composition_class,target_type,canonical_reference,eligible_sources_json,excluded_sources_json,discovery_sources_json,materialization_sources_json,fallback_sources_json,routing_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)").bind(routeId,input.projectId||null,input.itemId||null,input.collectionTermId||null,domain,input.universe||null,input.compositionClass||null,input.targetType||null,input.canonicalReference||null,JSON.stringify(input.eligibleSources||[]),JSON.stringify(input.excludedSources||[]),JSON.stringify(input.discoverySources||[]),JSON.stringify(input.materializationSources||[]),JSON.stringify(input.fallbackSources||[]),ts,ts).run();return{id:routeId,...input,projectDomain:domain};}

export async function getSourceRoutingPlan(env:Env,input:{projectId?:string;itemId?:string;collectionTermId?:string}){const where:string[]=[];const values:unknown[]=[];if(input.itemId){where.push("item_id=?");values.push(input.itemId)}if(input.projectId){where.push("project_id=?");values.push(input.projectId)}if(input.collectionTermId){where.push("collection_term_id=?");values.push(input.collectionTermId)}if(!where.length)return null;const row=await env.DB.prepare(`SELECT * FROM source_routing_plans WHERE ${where.join(" AND ")} ORDER BY routing_version DESC,updated_at DESC LIMIT 1`).bind(...values).first<Record<string,unknown>>();if(!row)return null;return{...row,eligibleSources:parse(row.eligible_sources_json,[]),excludedSources:parse(row.excluded_sources_json,[]),discoverySources:parse(row.discovery_sources_json,[]),materializationSources:parse(row.materialization_sources_json,[]),fallbackSources:parse(row.fallback_sources_json,[])};}
