import type { Env } from "../types";
import { id, nowMs } from "./ids";

async function digest(value:string){const data=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("");}
const j=(value:unknown,fallback:unknown={})=>{try{return JSON.parse(String(value??""))}catch{return fallback}};

export async function policyWorkspace(env:Env,projectId?:string){
  const projectWhere=projectId?" WHERE project_id=? OR project_id IS NULL":""; const args=projectId?[projectId]:[];
  const [gaps,policies,events]=await Promise.all([
    env.DB.prepare(`SELECT status,severity,category,COUNT(*) AS count FROM operational_gaps${projectWhere} GROUP BY status,severity,category ORDER BY status,severity`).bind(...args).all<Record<string,unknown>>(),
    env.DB.prepare(`SELECT status,category,COUNT(*) AS count,SUM(times_applied) AS applied,SUM(success_count) AS successes,SUM(failure_count) AS failures FROM operational_policies${projectWhere} GROUP BY status,category`).bind(...args).all<Record<string,unknown>>(),
    projectId?env.DB.prepare("SELECT * FROM operational_policy_events WHERE project_id=? ORDER BY created_at DESC LIMIT 100").bind(projectId).all<Record<string,unknown>>():env.DB.prepare("SELECT * FROM operational_policy_events ORDER BY created_at DESC LIMIT 100").all<Record<string,unknown>>()
  ]);
  return {projectId:projectId||null,gaps:gaps.results||[],policies:policies.results||[],recentEvents:events.results||[]};
}

export async function detectOperationalGap(env:Env,input:{category:string;severity?:string;projectId?:string;itemId?:string;domain?:string;universe?:string;compositionClass?:string;semanticClass?:string;preset?:string;source?:string;host?:string;tool?:string;workerType?:string;symptom:string;rootCause?:string;evidence?:unknown}){
  const normalized={category:input.category.trim().toUpperCase(),projectId:input.projectId||null,itemId:input.itemId||null,domain:input.domain||null,universe:input.universe||null,compositionClass:input.compositionClass||null,semanticClass:input.semanticClass||null,preset:input.preset||null,source:input.source||null,host:input.host||null,tool:input.tool||null,workerType:input.workerType||null,symptom:input.symptom.trim()};
  const signature=await digest(JSON.stringify(normalized)); const existing=await env.DB.prepare("SELECT * FROM operational_gaps WHERE signature=? AND status='OPEN' ORDER BY last_seen_at DESC LIMIT 1").bind(signature).first<Record<string,unknown>>(); const ts=nowMs();
  if(existing){await env.DB.prepare("UPDATE operational_gaps SET occurrence_count=occurrence_count+1,last_seen_at=?,evidence_json=?,root_cause=COALESCE(?,root_cause) WHERE id=?").bind(ts,JSON.stringify(input.evidence||{}),input.rootCause||null,existing.id).run();return env.DB.prepare("SELECT * FROM operational_gaps WHERE id=?").bind(existing.id).first<Record<string,unknown>>();}
  const gapId=id("GAP"); await env.DB.prepare(`INSERT INTO operational_gaps (id,signature,category,severity,project_id,item_id,domain,universe,composition_class,semantic_class,preset,source,host,tool,worker_type,symptom,root_cause,evidence_json,occurrence_count,status,first_seen_at,last_seen_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,'OPEN',?,?)`)
    .bind(gapId,signature,normalized.category,(input.severity||"MEDIUM").toUpperCase(),input.projectId||null,input.itemId||null,input.domain||null,input.universe||null,input.compositionClass||null,input.semanticClass||null,input.preset||null,input.source||null,input.host||null,input.tool||null,input.workerType||null,input.symptom.trim(),input.rootCause||null,JSON.stringify(input.evidence||{}),ts,ts).run();
  return env.DB.prepare("SELECT * FROM operational_gaps WHERE id=?").bind(gapId).first<Record<string,unknown>>();
}

export async function listOperationalGaps(env:Env,input:{status?:string;severity?:string;category?:string;projectId?:string;limit?:number}){
  const where:string[]=[]; const values:unknown[]=[]; if(input.status){where.push("status=?");values.push(input.status)}if(input.severity){where.push("severity=?");values.push(input.severity)}if(input.category){where.push("category=?");values.push(input.category)}if(input.projectId){where.push("project_id=?");values.push(input.projectId)}
  const sql=`SELECT * FROM operational_gaps${where.length?` WHERE ${where.join(" AND ")}`:""} ORDER BY CASE severity WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 ELSE 1 END DESC,last_seen_at DESC LIMIT ?`;values.push(Math.max(1,Math.min(input.limit||100,500)));const result=await env.DB.prepare(sql).bind(...values).all<Record<string,unknown>>();return result.results||[];
}
export async function getOperationalGap(env:Env,gapId:string){return env.DB.prepare("SELECT * FROM operational_gaps WHERE id=?").bind(gapId).first<Record<string,unknown>>();}

export async function createOperationalPolicy(env:Env,input:{policyKey?:string;name:string;description?:string;category:string;scopeLevel?:string;propagationLevel?:number;domain?:string;universe?:string;workType?:string;compositionClass?:string;semanticClass?:string;preset?:string;projectId?:string;itemId?:string;condition?:unknown;action?:unknown;priority?:number;confidence?:number;sourceGapId?:string;notes?:string}){
  const ts=nowMs();const policyId=id("POL");const policyKey=input.policyKey?.trim()||`policy-${policyId.toLowerCase()}`;
  await env.DB.prepare(`INSERT INTO operational_policies (id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,domain,universe,work_type,composition_class,semantic_class,preset,project_id,item_id,condition_json,action_json,priority,confidence,source_gap_id,created_by,version,notes,created_at,updated_at) VALUES (?,?,?,?,?,'DRAFT','LEARNED_POLICY',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'SUPERVISOR_MCP',1,?,?,?)`)
    .bind(policyId,policyKey,input.name.trim(),input.description||null,input.category.trim().toUpperCase(),input.scopeLevel||"PROJECT",Math.max(1,input.propagationLevel||1),input.domain||null,input.universe||null,input.workType||null,input.compositionClass||null,input.semanticClass||null,input.preset||null,input.projectId||null,input.itemId||null,JSON.stringify(input.condition||{}),JSON.stringify(input.action||{}),Math.max(1,input.priority||1),Math.max(0,Math.min(input.confidence??50,100)),input.sourceGapId||null,input.notes||null,ts,ts).run();
  if(input.sourceGapId)await env.DB.prepare("UPDATE operational_gaps SET resolution_policy_id=? WHERE id=?").bind(policyId,input.sourceGapId).run();
  return env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();
}

export async function editOperationalPolicy(env:Env,policyId:string,input:{name?:string;description?:string;condition?:unknown;action?:unknown;priority?:number;confidence?:number;notes?:string}){
  const current=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();if(!current)return null;const ts=nowMs();const nextId=id("POL");const version=Number(current.version||1)+1;
  await env.DB.batch([
    env.DB.prepare(`INSERT INTO operational_policies (id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,domain,universe,work_type,composition_class,semantic_class,preset,project_id,item_id,condition_json,action_json,priority,confidence,source_gap_id,created_by,version,previous_version_id,times_matched,times_applied,success_count,failure_count,avg_time_before_ms,avg_time_after_ms,approval_rate_before,approval_rate_after,cost_before,cost_after,notes,created_at,updated_at) VALUES (?,?,?,?,?,'DRAFT',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`)
      .bind(nextId,current.policy_key,input.name??current.name,input.description??current.description,current.category,current.rule_type,current.scope_level,current.propagation_level,current.domain,current.universe,current.work_type,current.composition_class,current.semantic_class,current.preset,current.project_id,current.item_id,JSON.stringify(input.condition??j(current.condition_json,{})),JSON.stringify(input.action??j(current.action_json,{})),input.priority??current.priority,input.confidence??current.confidence,current.source_gap_id,"SUPERVISOR_MCP",version,policyId,current.times_matched,current.times_applied,current.success_count,current.failure_count,current.avg_time_before_ms,current.avg_time_after_ms,current.approval_rate_before,current.approval_rate_after,current.cost_before,current.cost_after,input.notes??current.notes,ts,ts),
    env.DB.prepare("UPDATE operational_policies SET status='SUPERSEDED',updated_at=? WHERE id=?").bind(ts,policyId),
  ]);
  return env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(nextId).first<Record<string,unknown>>();
}

export async function setPolicyStatus(env:Env,policyId:string,status:string,eventType:string){const current=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();if(!current)return null;const ts=nowMs();await env.DB.batch([env.DB.prepare("UPDATE operational_policies SET status=?,updated_at=? WHERE id=?").bind(status,ts,policyId),env.DB.prepare("INSERT INTO operational_policy_events (id,policy_id,policy_version,gap_id,project_id,item_id,event_type,before_state_json,after_state_json,action_json,result,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(id("POLE"),policyId,current.version,current.source_gap_id||null,current.project_id||null,current.item_id||null,eventType,JSON.stringify({status:current.status}),JSON.stringify({status}),current.action_json||"{}","OK",ts)]);return env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();}

export async function rollbackPolicy(env:Env,policyId:string){const current=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();if(!current)return null;if(!current.previous_version_id)return {error:"NO_PREVIOUS_VERSION"};const previous=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(current.previous_version_id).first<Record<string,unknown>>();if(!previous)return {error:"PREVIOUS_NOT_FOUND"};const ts=nowMs();await env.DB.batch([env.DB.prepare("UPDATE operational_policies SET status='ROLLED_BACK',rollback_to_version=?,updated_at=? WHERE id=?").bind(previous.version,ts,policyId),env.DB.prepare("UPDATE operational_policies SET status='ACTIVE',updated_at=? WHERE id=?").bind(ts,previous.id),env.DB.prepare("INSERT INTO operational_policy_events (id,policy_id,policy_version,event_type,before_state_json,after_state_json,action_json,result,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id("POLE"),policyId,current.version,"ROLLBACK",JSON.stringify({current:policyId}),JSON.stringify({active:previous.id}),"{}","OK",ts)]);return {rolledBack:policyId,activePolicy:previous};}

export async function testPolicy(env:Env,policyId:string){const policy=await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>();if(!policy)return null;const where=["status='OPEN'"];const values:unknown[]=[];for(const [column,value] of [["project_id",policy.project_id],["domain",policy.domain],["universe",policy.universe],["composition_class",policy.composition_class],["semantic_class",policy.semantic_class],["preset",policy.preset]] as Array<[string,unknown]>){if(value){where.push(`${column}=?`);values.push(value)}}const result=await env.DB.prepare(`SELECT COUNT(*) AS matches,SUM(occurrence_count) AS occurrences FROM operational_gaps WHERE ${where.join(" AND ")}`).bind(...values).first<Record<string,unknown>>();return {policyId,status:policy.status,dryRun:true,condition:j(policy.condition_json,{}),action:j(policy.action_json,{}),matches:Number(result?.matches||0),occurrences:Number(result?.occurrences||0)};}

export async function listOperationalPolicies(env:Env,input:{status?:string;category?:string;projectId?:string;policyKey?:string;limit?:number}){const where:string[]=[];const values:unknown[]=[];if(input.status){where.push("status=?");values.push(input.status)}if(input.category){where.push("category=?");values.push(input.category)}if(input.projectId){where.push("project_id=?");values.push(input.projectId)}if(input.policyKey){where.push("policy_key=?");values.push(input.policyKey)}values.push(Math.max(1,Math.min(input.limit||100,500)));const result=await env.DB.prepare(`SELECT * FROM operational_policies${where.length?` WHERE ${where.join(" AND ")}`:""} ORDER BY updated_at DESC LIMIT ?`).bind(...values).all<Record<string,unknown>>();return result.results||[];}
export async function appliedPolicies(env:Env,projectId?:string,limit=200){const result=projectId?await env.DB.prepare("SELECT * FROM operational_policy_events WHERE project_id=? ORDER BY created_at DESC LIMIT ?").bind(projectId,limit).all<Record<string,unknown>>():await env.DB.prepare("SELECT * FROM operational_policy_events ORDER BY created_at DESC LIMIT ?").bind(limit).all<Record<string,unknown>>();return result.results||[];}
export async function linkGapPolicy(env:Env,gapId:string,policyId:string){const [gap,policy]=await Promise.all([getOperationalGap(env,gapId),env.DB.prepare("SELECT id FROM operational_policies WHERE id=?").bind(policyId).first()]);if(!gap||!policy)return null;await env.DB.prepare("UPDATE operational_gaps SET resolution_policy_id=?,last_seen_at=? WHERE id=?").bind(policyId,nowMs(),gapId).run();return getOperationalGap(env,gapId);}
export async function policyTelemetry(env:Env){const [summary,events]=await env.DB.batch([env.DB.prepare("SELECT status,COUNT(*) AS policies,SUM(times_matched) AS matched,SUM(times_applied) AS applied,SUM(success_count) AS successes,SUM(failure_count) AS failures FROM operational_policies GROUP BY status"),env.DB.prepare("SELECT event_type,COUNT(*) AS count,SUM(time_saved_ms) AS time_saved_ms,SUM(requests_saved) AS requests_saved,SUM(external_requests_saved) AS external_requests_saved,SUM(false_positive) AS false_positives FROM operational_policy_events GROUP BY event_type")]);return {policies:summary.results||[],events:events.results||[]};}

export async function resolveGapAndLearn(env:Env,gapId:string,input:{policyName?:string;action?:unknown;condition?:unknown;confidence?:number}){const gap=await getOperationalGap(env,gapId);if(!gap)return null;let policyId=gap.resolution_policy_id?String(gap.resolution_policy_id):null;if(!policyId){const policy=await createOperationalPolicy(env,{name:input.policyName||`Resolver ${String(gap.category)}`,category:String(gap.category),projectId:gap.project_id?String(gap.project_id):undefined,itemId:gap.item_id?String(gap.item_id):undefined,domain:gap.domain?String(gap.domain):undefined,universe:gap.universe?String(gap.universe):undefined,compositionClass:gap.composition_class?String(gap.composition_class):undefined,semanticClass:gap.semantic_class?String(gap.semantic_class):undefined,preset:gap.preset?String(gap.preset):undefined,condition:input.condition||{signature:gap.signature},action:input.action||{},confidence:input.confidence||70,sourceGapId:gapId});policyId=String(policy?.id||"");}
  const ts=nowMs();await env.DB.batch([env.DB.prepare("UPDATE operational_gaps SET status='RESOLVED',resolution_policy_id=?,last_seen_at=? WHERE id=?").bind(policyId,ts,gapId),env.DB.prepare("INSERT INTO operational_policy_events (id,policy_id,gap_id,project_id,item_id,event_type,before_state_json,after_state_json,action_json,result,created_at) VALUES (?,?,?,?,?,'GAP_RESOLVED',?,?,?,?,?)").bind(id("POLE"),policyId||null,gapId,gap.project_id||null,gap.item_id||null,JSON.stringify({status:gap.status}),JSON.stringify({status:"RESOLVED"}),JSON.stringify(input.action||{}),"OK",ts)]);return {gap:await getOperationalGap(env,gapId),policy:policyId?await env.DB.prepare("SELECT * FROM operational_policies WHERE id=?").bind(policyId).first<Record<string,unknown>>():null};}
