import type { Env } from "../types";
import { id, nowMs } from "./ids";

export async function stockPanel(env:Env){
  const [totals,universes,rotation,policies]=await env.DB.batch([
    env.DB.prepare("SELECT status,COUNT(*) AS count,SUM(size_bytes) AS bytes,SUM(use_count) AS uses FROM assets GROUP BY status"),
    env.DB.prepare("SELECT universe,COUNT(*) AS count,SUM(CASE WHEN status='Aprovado' THEN 1 ELSE 0 END) AS approved,SUM(use_count) AS uses FROM assets GROUP BY universe ORDER BY approved DESC,universe"),
    env.DB.prepare("SELECT CASE WHEN use_count=0 THEN 'NEVER_USED' WHEN last_used_at IS NULL THEN 'UNKNOWN' WHEN last_used_at<? THEN 'COLD' ELSE 'ACTIVE' END AS bucket,COUNT(*) AS count FROM assets WHERE status='Aprovado' GROUP BY bucket").bind(nowMs()-60*24*3600_000),
    env.DB.prepare("SELECT * FROM semantic_stock_policies WHERE active=1 ORDER BY universe,concept")
  ]);
  return {totals:totals.results||[],universes:universes.results||[],rotation:rotation.results||[],policies:policies.results||[]};
}
export async function configureStockPolicy(env:Env,input:{id?:string;concept:string;universe?:string;kind?:string;minimum?:number;ideal?:number;maximum?:number;active?:boolean}){
 const ts=nowMs(),pid=input.id||id("STPOL");await env.DB.prepare("INSERT INTO semantic_stock_policies (id,concept,universe,kind,minimum,ideal,maximum,active,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET concept=excluded.concept,universe=excluded.universe,kind=excluded.kind,minimum=excluded.minimum,ideal=excluded.ideal,maximum=excluded.maximum,active=excluded.active,updated_at=excluded.updated_at").bind(pid,input.concept,input.universe||"Sem universo",input.kind||"Todos",input.minimum??3,input.ideal??5,input.maximum??10,input.active===false?0:1,ts).run();return env.DB.prepare("SELECT * FROM semantic_stock_policies WHERE id=?").bind(pid).first<Record<string,unknown>>();
}
export async function registerAssetConsultation(env:Env,input:{assetId?:string;concept:string;project?:string;query?:string;selected?:boolean}){const cid=id("CONS");await env.DB.prepare("INSERT INTO asset_consultations (id,asset_id,concept,project,query,selected,created_at) VALUES (?,?,?,?,?,?,?)").bind(cid,input.assetId||null,input.concept,input.project||null,input.query||null,input.selected?1:0,nowMs()).run();return {id:cid};}
export async function evaluateCollectionNeed(env:Env,input:{concept:string;universe?:string;kind?:string}){const universe=input.universe||"Sem universo",kind=input.kind||"Todos";const policy=await env.DB.prepare("SELECT * FROM semantic_stock_policies WHERE active=1 AND concept=? AND universe IN (?, 'Sem universo') AND kind IN (?, 'Todos') ORDER BY CASE WHEN universe=? THEN 0 ELSE 1 END,CASE WHEN kind=? THEN 0 ELSE 1 END LIMIT 1").bind(input.concept,universe,kind,universe,kind).first<Record<string,unknown>>();const countRow=await env.DB.prepare("SELECT COUNT(*) AS count FROM assets WHERE status='Aprovado' AND (subject=? OR name LIKE ? OR tags LIKE ?) AND (?='Sem universo' OR universe=?) AND (?='Todos' OR kind=?)").bind(input.concept,`%${input.concept}%`,`%${input.concept}%`,universe,universe,kind,kind).first<{count:number}>();const count=Number(countRow?.count||0),minimum=Number(policy?.minimum??3),ideal=Number(policy?.ideal??5),maximum=Number(policy?.maximum??10);return {concept:input.concept,universe,kind,count,minimum,ideal,maximum,needsCollection:count<minimum,target:Math.max(0,ideal-count),overstock:count>maximum,policy:policy||null};}
export async function stockTextReport(env:Env){const p=await stockPanel(env);const lines=["CORVO LIBRARY V2 — ESTOQUE",...p.totals.map((r:any)=>`${r.status}: ${r.count} assets / ${r.uses||0} usos`),"",`Universos: ${p.universes.length}`,`Políticas ativas: ${p.policies.length}`];return lines.join("\n");}
