-- 0.20.41 — Políticas operacionais persistentes + seed dos presets
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS v2_project_policy_links (
  id TEXT PRIMARY KEY NOT NULL,
  project_id TEXT NOT NULL REFERENCES automatic_projects(id) ON DELETE CASCADE,
  policy_id TEXT NOT NULL REFERENCES operational_policies(id) ON DELETE CASCADE,
  active INTEGER NOT NULL DEFAULT 1,
  created_by TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  removed_at INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_v2_project_policy_link_unique ON v2_project_policy_links(project_id,policy_id);
CREATE INDEX IF NOT EXISTS idx_v2_project_policy_link_active ON v2_project_policy_links(project_id,active,updated_at DESC);

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-3OP-4X3','PRESET_3_OPCOES_4X3','3 opções — imagem contextual 4:3','A imagem contextual principal deve funcionar em quadro 4:3. Imagens maiores podem ser cortadas. Evitar retrato vertical estreito, sujeito pequeno ou excesso de vazio. O crop não pode destruir o sujeito principal.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'3_OPCOES','{"target_id":"3_OPCOES"}','{"instruction":"A imagem contextual principal deve funcionar em quadro 4:3. Imagens maiores podem ser cortadas. Evitar retrato vertical estreito, sujeito pequeno ou excesso de vazio. O crop não pode destruir o sujeito principal.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_3_OPCOES_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-3OP-RES','PRESET_3_OPCOES_RESULT_4X3','3 opções — resultado 4:3','Quando a etapa de resultado apresentar imagem, usar imagem de resultado compatível com 4:3, com boa ocupação do quadro.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'3_OPCOES','{"target_id":"3_OPCOES"}','{"instruction":"Quando a etapa de resultado apresentar imagem, usar imagem de resultado compatível com 4:3, com boa ocupação do quadro.","metadata":{},"asset_requirement":"result_4x3","applies_to":["IMAGEM_RESULTADO","RESULTADO","RESULT"]}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_3_OPCOES_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-VF-4X3','PRESET_VF_4X3','Verdadeiro/Falso — contextual 4:3','A imagem contextual deve funcionar em 4:3. Pode cortar uma imagem maior. Evitar retrato estreito e composição com muito espaço vazio.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'VERDADEIRO_FALSO','{"target_id":"VERDADEIRO_FALSO"}','{"instruction":"A imagem contextual deve funcionar em 4:3. Pode cortar uma imagem maior. Evitar retrato estreito e composição com muito espaço vazio.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_VF_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-VF-RES','PRESET_VF_RESULT_4X3','Verdadeiro/Falso — resultado 4:3','Quando houver imagem de resultado, usar imagem 4:3 ou crop-safe para 4:3.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'VERDADEIRO_FALSO','{"target_id":"VERDADEIRO_FALSO"}','{"instruction":"Quando houver imagem de resultado, usar imagem 4:3 ou crop-safe para 4:3.","metadata":{},"asset_requirement":"result_4x3","applies_to":["IMAGEM_RESULTADO","RESULTADO","RESULT"]}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_VF_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-PREF-4X3','PRESET_PREFERE_4X3','Qual você prefere — imagens A/B 4:3','As duas imagens A/B devem funcionar em cards 4:3. Podem ser cortadas a partir de imagens maiores. Evitar retratos estreitos, sujeitos pequenos e enquadramentos que criem grandes áreas vazias.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'QUAL_VOCE_PREFERE','{"target_id":"QUAL_VOCE_PREFERE"}','{"instruction":"As duas imagens A/B devem funcionar em cards 4:3. Podem ser cortadas a partir de imagens maiores. Evitar retratos estreitos, sujeitos pequenos e enquadramentos que criem grandes áreas vazias.","metadata":{},"asset_requirement":"raster_4x3","applies_to":["IMAGEM_A","IMAGEM_B"]}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_PREFERE_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-PREF-RES','PRESET_PREFERE_RESULT_4X3','Qual você prefere — resultado 4:3','Se a etapa de resultado usar imagem, validar também o resultado separadamente e usar composição compatível com 4:3.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'QUAL_VOCE_PREFERE','{"target_id":"QUAL_VOCE_PREFERE"}','{"instruction":"Se a etapa de resultado usar imagem, validar também o resultado separadamente e usar composição compatível com 4:3.","metadata":{},"asset_requirement":"result_4x3","applies_to":["IMAGEM_RESULTADO","RESULTADO","RESULT"]}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_PREFERE_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-LOGO-4X3','PRESET_LOGO_4X3','Logo — área 4:3','A imagem usada pelo preset deve ser compatível com área 4:3. Imagens maiores podem ser cortadas desde que o logo/elemento principal permaneça inteiro e legível.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'LOGO','{"target_id":"LOGO"}','{"instruction":"A imagem usada pelo preset deve ser compatível com área 4:3. Imagens maiores podem ser cortadas desde que o logo/elemento principal permaneça inteiro e legível.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_LOGO_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-LOGO-RES','PRESET_LOGO_RESULT_4X3','Logo resultado — 4:3','A imagem de revelação/resultado deve funcionar em 4:3 e manter o elemento principal legível.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'LOGO_RESULTADO','{"target_id":"LOGO_RESULTADO"}','{"instruction":"A imagem de revelação/resultado deve funcionar em 4:3 e manter o elemento principal legível.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_LOGO_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-CENTRAL2','PRESET_CENTRAL_2_TRANSPARENT','Central + 2 exige transparência','A imagem principal central e as duas opções devem ser assets isolados com transparência real. Não usar cena contextual completa com fundo. Pode remover somente fundo simples quando a referência estiver correta. Não criar composição artificial.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'CENTRAL_2','{"target_id":"CENTRAL_2"}','{"instruction":"A imagem principal central e as duas opções devem ser assets isolados com transparência real. Não usar cena contextual completa com fundo. Pode remover somente fundo simples quando a referência estiver correta. Não criar composição artificial.","metadata":{},"asset_requirements":{"IMAGEM_PRINCIPAL":"transparent_subject","IMAGEM_1":"transparent_option","IMAGEM_2":"transparent_option"}}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_CENTRAL_2_TRANSPARENT' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-FOCO4','PRESET_FOCO_4_TRANSPARENT','Foco + 4 exige transparência','A imagem principal e as quatro opções devem ser assets isolados com transparência real. Não usar cena completa com fundo. Não compor localmente. Quando necessário, remover apenas fundo simples de uma referência semanticamente correta.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'FOCO_4','{"target_id":"FOCO_4"}','{"instruction":"A imagem principal e as quatro opções devem ser assets isolados com transparência real. Não usar cena completa com fundo. Não compor localmente. Quando necessário, remover apenas fundo simples de uma referência semanticamente correta.","metadata":{},"asset_requirements":{"IMAGEM_PRINCIPAL":"transparent_subject","IMAGEM_1":"transparent_option","IMAGEM_2":"transparent_option","IMAGEM_3":"transparent_option","IMAGEM_4":"transparent_option"}}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_FOCO_4_TRANSPARENT' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-EMOJI-HINT','PRESET_EMOJI_HINTS_TRANSPARENT','Emoji Quiz — pistas transparentes','As imagens da etapa de pistas não são cenas completas. Devem ser dicas visuais isoladas, simples e reconhecíveis, preferencialmente com transparência real. Cada pista deve representar um elemento útil para a adivinhação.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'EMOJI_QUIZ','{"target_id":"EMOJI_QUIZ"}','{"instruction":"As imagens da etapa de pistas não são cenas completas. Devem ser dicas visuais isoladas, simples e reconhecíveis, preferencialmente com transparência real. Cada pista deve representar um elemento útil para a adivinhação.","metadata":{},"asset_requirement":"transparent_hint"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_EMOJI_HINTS_TRANSPARENT' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-EMOJI-RES4','PRESET_EMOJI_RESULT_4X3','Emoji Quiz — resultado 4:3','A etapa de resultado normalmente pode apresentar uma imagem completa do personagem, obra, objeto ou resposta. Usar imagem 4:3 ou crop-safe para 4:3, salvo política mais específica.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'EMOJI_QUIZ','{"target_id":"EMOJI_QUIZ"}','{"instruction":"A etapa de resultado normalmente pode apresentar uma imagem completa do personagem, obra, objeto ou resposta. Usar imagem 4:3 ou crop-safe para 4:3, salvo política mais específica.","metadata":{},"asset_requirement":"result_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_EMOJI_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-EMOJI-REVEAL','PRESET_EMOJI_RESULT_REVEAL','Emoji resultado — revelação','A revelação deve apresentar a resposta visual de forma clara. Por padrão, usar raster 4:3/crop-safe; as pistas anteriores continuam sendo transparent_hint.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'EMOJI_RESULTADO','{"target_id":"EMOJI_RESULTADO"}','{"instruction":"A revelação deve apresentar a resposta visual de forma clara. Por padrão, usar raster 4:3/crop-safe; as pistas anteriores continuam sendo transparent_hint.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_EMOJI_RESULT_REVEAL' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-FILME-HINT','PRESET_FILME_HINTS_TRANSPARENT','Filme — pistas transparentes','As imagens de pista devem ser elementos visuais isolados e reconhecíveis, não uma cena completa do filme. Preferir assets com transparência real. As pistas devem ajudar o jogador a inferir a obra sem revelar diretamente a resposta.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'FILME','{"target_id":"FILME"}','{"instruction":"As imagens de pista devem ser elementos visuais isolados e reconhecíveis, não uma cena completa do filme. Preferir assets com transparência real. As pistas devem ajudar o jogador a inferir a obra sem revelar diretamente a resposta.","metadata":{},"asset_requirement":"transparent_hint"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_FILME_HINTS_TRANSPARENT' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-FILME-RES4','PRESET_FILME_RESULT_4X3','Filme — resultado 4:3','A etapa de resultado pode apresentar imagem completa da obra/resposta em 4:3 ou crop-safe para 4:3.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'FILME','{"target_id":"FILME"}','{"instruction":"A etapa de resultado pode apresentar imagem completa da obra/resposta em 4:3 ou crop-safe para 4:3.","metadata":{},"asset_requirement":"result_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_FILME_RESULT_4X3' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-FILME-REVEAL','PRESET_FILME_RESULT_REVEAL','Filme resultado — revelação','A imagem de revelação deve representar claramente o filme/resposta e funcionar em raster 4:3, salvo regra específica do projeto.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','PRESET',200,'FILME_RESULTADO','{"target_id":"FILME_RESULTADO"}','{"instruction":"A imagem de revelação deve representar claramente o filme/resposta e funcionar em raster 4:3, salvo regra específica do projeto.","metadata":{},"asset_requirement":"raster_4x3"}',50,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='PRESET_FILME_RESULT_REVEAL' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-GLOBAL-RESULT','RESULT_IMAGE_MUST_BE_VALIDATED_SEPARATELY','Resultado visual passa por QA separado','Imagens de resultado são slots visuais independentes e também passam por QA. Não considerar a pergunta aprovada apenas porque a imagem principal está correta. Quando houver resultado visual, validar referência, enquadramento, formato e compatibilidade com o preset.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','GLOBAL',100,NULL,'{"target_id":"GLOBAL"}','{"instruction":"Imagens de resultado são slots visuais independentes e também passam por QA. Não considerar a pergunta aprovada apenas porque a imagem principal está correta. Quando houver resultado visual, validar referência, enquadramento, formato e compatibilidade com o preset.","metadata":{},"asset_requirement":"result_4x3","applies_to":["IMAGEM_RESULTADO","RESULTADO","RESULT"]}',40,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='RESULT_IMAGE_MUST_BE_VALIDATED_SEPARATELY' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-GLOBAL-CROP','RASTER_4X3_CROP_ALLOWED','Crop 4:3 permitido quando seguro','Para slots raster_4x3, uma imagem maior ou em proporção diferente pode ser usada quando existir crop seguro para 4:3. O crop é ajuste técnico permitido. Não aceitar crop que corte rosto, sujeito principal, objeto essencial ou torne a composição ruim.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','GLOBAL',100,NULL,'{"target_id":"GLOBAL"}','{"instruction":"Para slots raster_4x3, uma imagem maior ou em proporção diferente pode ser usada quando existir crop seguro para 4:3. O crop é ajuste técnico permitido. Não aceitar crop que corte rosto, sujeito principal, objeto essencial ou torne a composição ruim.","metadata":{}}',40,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='RASTER_4X3_CROP_ALLOWED' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-GLOBAL-TRANS','TRANSPARENCY_REAL_REQUIRED','Transparência real obrigatória','Quando o slot exigir transparent_subject, transparent_option ou transparent_hint, a transparência deve ser real. Rejeitar checkerboard incorporado, fundo branco fingindo transparência, halo forte, fragmentos de fundo ou bordas contaminadas.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','GLOBAL',100,NULL,'{"target_id":"GLOBAL"}','{"instruction":"Quando o slot exigir transparent_subject, transparent_option ou transparent_hint, a transparência deve ser real. Rejeitar checkerboard incorporado, fundo branco fingindo transparência, halo forte, fragmentos de fundo ou bordas contaminadas.","metadata":{}}',40,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='TRANSPARENCY_REAL_REQUIRED' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT INTO operational_policies(id,policy_key,name,description,category,status,rule_type,scope_level,propagation_level,preset,condition_json,action_json,priority,confidence,created_by,version,notes,created_at,updated_at)
SELECT 'POL-SEED-GLOBAL-NOCOMP','NO_VISUAL_COMPOSITION_FALLBACK','Não fabricar composição como fallback','Quando a representação correta não existir pronta, não montar, combinar, adicionar objetos ou fabricar composição como fallback. Procurar outra referência/candidata ou relinkar.','OPERATIONAL_CONTEXT','ACTIVE','PERSISTENT_CONTEXT_POLICY','GLOBAL',100,NULL,'{"target_id":"GLOBAL"}','{"instruction":"Quando a representação correta não existir pronta, não montar, combinar, adicionar objetos ou fabricar composição como fallback. Procurar outra referência/candidata ou relinkar.","metadata":{}}',40,100,'SYSTEM_SEED',1,'Seed operacional obrigatório dos presets',unixepoch('now')*1000,unixepoch('now')*1000
WHERE NOT EXISTS (SELECT 1 FROM operational_policies WHERE policy_key='NO_VISUAL_COMPOSITION_FALLBACK' AND rule_type='PERSISTENT_CONTEXT_POLICY' AND status!='DELETED');

INSERT OR REPLACE INTO v2_schema_meta(key,value,updated_at) VALUES ('operational_policy_seed_version','PRESET_POLICY_SEED_V1',unixepoch('now')*1000);
INSERT OR REPLACE INTO v2_schema_meta(key,value,updated_at) VALUES ('operational_policy_revision',CAST(unixepoch('now')*1000 AS TEXT),unixepoch('now')*1000);
INSERT OR REPLACE INTO v2_schema_meta(key,value,updated_at) VALUES ('schema_version','2.24.0',unixepoch('now')*1000);
