from pathlib import Path
import json, re
root=Path(__file__).resolve().parents[1]
checks=[]
def check(name, cond, detail=''):
    checks.append({'name':name,'pass':bool(cond),'detail':detail})
page=(root/'app/page.tsx').read_text()
index=(root/'cloudflare/src/index.ts').read_text()
auth=(root/'cloudflare/src/core/auth.ts').read_text()
control=(root/'lib/cloudflare-control.ts').read_text()
recover=(root/'app/api/setup/cloudflare/recover-browser/route.ts').read_text()
provision=(root/'app/api/setup/cloudflare/provision/route.ts').read_text()
generated=(root/'lib/generated-core-bundle.ts').read_text()
package=json.loads((root/'package.json').read_text())
core_package=json.loads((root/'cloudflare/package.json').read_text())
check('app version 0.20.55',package.get('version')=='0.20.55')
check('core version 0.20.55',core_package.get('version')=='0.20.55')
check('settings bypasses authoritative data gate','(dataReady || currentView === "Configurações")' in page)
check('boot blocker hidden in settings','currentView !== "Configurações"' in page and 'authoritativeBoot' in page)
check('unauthorized is classified as browser session','SESSION_UNAUTHORIZED' in page and 'BROWSER_SESSION_INVALID' in page)
check('settings contains session recovery UI','RECUPERAÇÃO DE SESSÃO' in page and 'Recuperar acesso deste navegador' in page)
check('recovery updates only browser connection','saveBrowserConnection(nextConnection)' in page and 'browserToken' in page)
check('version route public and d1 free','d1_read_required:false' in index and 'auth_mode:"DEVICE_TOKEN_V1"' in index)
check('version route is before auth',index.find('url.pathname === "/version"') < index.find('if (!await authorized'))
check('pair route is before auth',index.find('url.pathname === "/control/pair-browser"') < index.find('if (!await authorized'))
check('pair route requires control token','validControlPairingRequest(request, env)' in index)
check('browser device token supported','DEVICE_TOKEN_PREFIX = "corvo-device-v1"' in auth and 'validBrowserDeviceToken' in auth)
check('legacy app key remains compatible','env.CORVO_APP_KEY' in auth and 'await validBrowserDeviceToken' in auth)
check('device token uses internal-key hmac','hmac(message, internalKey(env))' in auth)
check('device tokens expire','DEVICE_TOKEN_TTL_SECONDS' in auth and 'payload.exp' in auth)
check('recovery route does not read D1','getOrCreateD1' not in recover and '.DB.' not in recover)
check('recovery refreshes control token only','"CLOUDFLARE_CONTROL_TOKEN"' in recover and 'putWorkerSecretWithToken(apiToken,accountId,workerName,"CORVO_APP_KEY"' not in recover and 'putWorkerSecretWithToken(apiToken,accountId,workerName,"CORVO_INTERNAL_KEY"' not in recover and 'putWorkerSecretWithToken(apiToken,accountId,workerName,"CORVO_SIGNING_KEY"' not in recover)
check('recovery preserves worker bindings','updateWorkerBundlePreservingBindings' in recover)
check('keep_bindings preserves secrets and data bindings','keep_bindings' in control and '"secret_text"' in control and '"d1"' in control and '"r2_bucket"' in control and '"queue"' in control)
check('existing worker setup does not regenerate secrets','if(existed)' in provision and 'updateWorkerBundlePreservingBindings' in provision)
check('existing worker gets per-browser pairing','pairBrowser(coreUrl,apiToken' in provision)
check('fresh worker still creates secrets','const legacyAppKey = randomSecret(32)' in provision and 'const internalKey = randomSecret(32)' in provision)
check('provision returns device token to browser','appKey:browserToken' in provision)
check('generated bundle remains fail-safe UNBUILT','CORE_WORKER_BUNDLE_VERSION: string = "UNBUILT"' in generated and '0.20.55' in generated)
check('recovery route validates workers.dev','CORE_URL_NOT_ALLOWED' in recover and '.workers.dev' in recover)
check('recovery never deletes or recreates infra','delete' not in recover.lower() and 'getOrCreate' not in recover)
passed=sum(x['pass'] for x in checks)
result={'version':'0.20.55','passed':passed,'total':len(checks),'ok':passed==len(checks),'checks':checks}
out=root/'BEHAVIOR_GATE_0_20_55_AUTH_RECOVERY_SETTINGS_BYPASS.json'
out.write_text(json.dumps(result,indent=2,ensure_ascii=False))
print(json.dumps(result,indent=2,ensure_ascii=False))
raise SystemExit(0 if result['ok'] else 1)
