from pathlib import Path
import json,re,sys
root=Path(__file__).resolve().parents[1]
checks=[]
def check(name,ok): checks.append({'name':name,'ok':bool(ok)}); print(('PASS' if ok else 'FAIL'),name)
package=json.loads((root/'package.json').read_text())
core_package=json.loads((root/'cloudflare/package.json').read_text())
page=(root/'app/page.tsx').read_text()
css=(root/'app/globals.css').read_text()
projects=(root/'cloudflare/src/core/projects.ts').read_text()
workflow=(root/'cloudflare/src/core/project-workflow.ts').read_text()
mcp=(root/'cloudflare/src/mcp.ts').read_text()
index=(root/'cloudflare/src/index.ts').read_text()
contracts=(root/'lib/contracts.ts').read_text()
short_route=(root/'app/api/projects/[id]/short/route.ts').read_text()
block_route=(root/'app/api/projects/[id]/blockers/route.ts').read_text()
check('app version 0.20.56',package.get('version')=='0.20.56')
check('core version 0.20.56',core_package.get('version')=='0.20.56')
check('schema remains 2.27.0','2.27.0' in index)
check('manual refresh state exists','projectRefreshBusy' in page and 'projectLastRefreshAt' in page)
check('manual refresh button exists','projectRefreshButton' in page and 'refreshSelectedProject()' in page and '"Atualizar"' in page)
check('refresh uses short state-version probe','/short?sinceVersion=${version}' in page and 'probeValue?.not_modified' in page)
check('no project slot background timer','slotTimer' not in page and 'artifactTimer' not in page and 'finalTimer' not in page)
check('no projects 8s polling','setInterval(()=>void refreshRecords("Projetos"),8000)' not in page)
check('explicit no-polling note','no background polling here' in page)
check('short HTTP app route exists','/short${query}' in short_route)
check('short HTTP core route exists','/projects\\/[^/]+\\/short$' in index and 'getShortOperationalSnapshot' in index)
check('blockers HTTP app route exists','/blockers`' in block_route)
check('blockers HTTP core route exists','/projects\\/[^/]+\\/blockers$' in index and 'getProjectBlockers' in index)
check('MCP blocker route exists','server.registerTool("obter_pendencias_projeto"' in mcp)
check('MCP blocker route marked fast','FAST BLOCKER SUMMARY' in mcp)
check('blocker summary avoids R2','FAST_BLOCKERS_INDEXED_NO_R2_NO_CANDIDATES_NO_POLICIES' in projects)
check('blockers include pending','PRODUCTION_SLOTS_PENDING' in projects)
check('blockers include relink','PRODUCTION_SLOTS_RELINK_REQUIRED' in projects)
check('blockers include QA','PRODUCTION_SLOTS_ASSIGNED_FOR_QA' in projects)
check('blockers include final images zip','IMAGES_ZIP_NOT_READY' in projects)
check('blockers include final script txt','SCRIPT_TXT_NOT_READY' in projects)
check('thumb/title marked optional in blocker output','optional:{thumbs:true,titles:true,publication_zip:true}' in projects)
check('production pending exposed in contract','production_slots_pending?:number' in contracts)
check('project slot query computes pending','production_slots_pending' in workflow)
check('collector slot follows production truth','abastecidos · ${productionPending} sem imagem' in workflow)
check('UI has obvious blocker heading','O QUE FALTA PARA CONCLUIR' in page)
check('UI shows next owner','Próxima frente:' in page)
check('UI labels optional media','não bloqueiam conclusão' in page)
check('slot header separates required/optional','obrigatórios ·' in page and 'opcionais' in page)
check('overall header uses required progress','progresso obrigatório' in page)
check('refresh UI explains D1 savings','Sem polling automático · economiza D1' in page)
check('refresh CSS exists','.projectRefreshButton{' in css)
check('blocker CSS exists','.projectBlockerSummary{' in css and '.projectBlockerItem.danger' in css)
check('CSS braces balanced',css.count('{')==css.count('}'))
check('core version exposed 0.20.56','core_version:"0.20.56"' in mcp and 'core_version:"0.20.56"' in index)
passed=sum(c['ok'] for c in checks)
result={'version':'0.20.56','passed':passed,'total':len(checks),'ok':passed==len(checks),'checks':checks}
(root/'BEHAVIOR_GATE_0_20_56_PROJECT_REFRESH_BLOCKERS.json').write_text(json.dumps(result,indent=2,ensure_ascii=False))
print(json.dumps({'passed':passed,'total':len(checks),'ok':result['ok']}))
sys.exit(0 if result['ok'] else 1)
